IDAES/idaes-pse

idaes/power_generation/unit_models/drum1D.py
fixing or correcting parameter declaration in health code
removed reference object
- fixing or correcting parameter declaration in health code
- removed reference object
-
=> Drum1D: fixing parameter declaration

docs/technical_specs/model_libraries/power_generation/costing/power_plant_costing.rst, docs/technical_specs/model_libraries/power_generation/flowsheets/subcritical_power_plant.rst, idaes/power_generation/costing/power_plant_costing.py, idaes/power_generation/flowsheets/subcritical_power_plant/subcritical_power_plant.py
Fixes minor documentation typos, and upper bound for costing module
Fix power plant documentation description
improve upper bound on power plant costing variables
- Fix power plant costing documentation
- Correct dynamic simulation description
- improve power plant costing upper bounds …
=> Power Plant documentation improvements

idaes/power_generation/properties/__init__.py, idaes/power_generation/properties/natural_gas_PR.py, idaes/power_generation/properties/tests/test_NG_PR.py
- To add the natural gas property package used in the NGFC example to idaes-pse.
- Added a generic property package for natural gas using the Peng Robinson EOS
- Added tests for the property package
=> Natural gas properties

idaes/config.py, idaes/generic_models/properties/cubic_eos/tests/test_cubic_root.py
Updated the extensions version.  The new version has some additional cubic equation root calculating functions.  Added tests for new functions too. 
=> Bump Extensions Version

idaes/commands/examples.py, idaes/commands/tests/test_commands.py
These failures occur on new install
- Fix the tests (underlying code is OK)
=> Fix command "get-examples" test failures

idaes/config.py
There was a minor bug fixed in k_aug recently.  This updates the default binary release to pick up that fix.  Otherwise there shouldn't be any changes from the 2.4.0 binaries. 
=> Update the binaries version to pick up a recent k_aug change.

idaes/generic_models/unit_models/pressure_changer.py, idaes/generic_models/unit_models/valve.py
=> Fix the valve initialization

idaes/core/__init__.py, idaes/generic_models/properties/core/eos/enrtl.py, idaes/generic_models/properties/core/eos/enrtl_submethods.py, idaes/generic_models/properties/core/eos/tests/test_enrtl.py, idaes/generic_models/properties/core/generic/generic_property.py
This adds a module for the generic property package framework that implements the eNRTL model. The first part adds the binary interaction parameters required for the local interaction contribution to the activity coefficient.
- alpha and tau parameters for eNRTL model
- calculation of X, Y, alpha, G and tau in state blocks
- verification tests for the above
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have …
=> ENRTL Model Part 1

idaes/dmf/codesearch.py
=> Model Library

idaes/generic_models/properties/helmholtz/helmholtz.py
=> Helmholtz thermo expr for v fix mw

idaes/config.py
This is an important fix.  I left the handler out of the new default config, so you won't see log messages by default.  This corrects the issue.
=> Fix missing console log handler

docs/user_guide/modeling_extensions/matopt/index.rst
NA
MatOpt documentation change
-
-
=> MatOpt documentation update

idaes/generic_models/properties/interrogator/properties_interrogator.py, idaes/generic_models/properties/interrogator/tests/test_properties_interrogator.py
There were a couple of bare exceptions in the code. This fixes them.
- 
-
=> Fixing some bare Exceptions

idaes/power_generation/costing/tests/test_NGCC_costing.py
Adds tests to the costing framework
Improves costing framework testing
- Adding two methods to test the implementation of NGCC power plant costing
-
=> Adding tests methods to the capital costing framework (NGCC power plant capital costing)

idaes/power_generation/costing/power_plant_costing.py, idaes/power_generation/flowsheets/ngcc/ngcc.py, idaes/power_generation/flowsheets/ngcc/ngcc_costing.py
=> adding NGCC costing TPC and O&M

idaes/power_generation/unit_models/helm/turbine_outlet.py
This let's you change the TEL curve for the steam turbine.  This will change with turbine size, but we were stuck with a fixed curve. 
=> Allow changing parameters for TEL curve

idaes/power_generation/unit_models/isothermal_sofc.py
Add initial isothermal soec model
=> Add initial isothermal sofc model

setup.py
Updating the Pyomo tag to the Pyomo 6.1.1 release.
-
-
=> Update Pyomo version

idaes/generic_models/properties/core/state_definitions/FPhx.py, idaes/generic_models/properties/core/state_definitions/FTPx.py, idaes/generic_models/properties/core/state_definitions/FcPh.py, idaes/generic_models/properties/core/state_definitions/FcTP.py
Fixed deprecation warnings due to Pyomo updates (and maybe some others).
-
-
=> Fixing some deprecation warnings

idaes/power_generation/flowsheets/soec/soec.py, idaes/power_generation/flowsheets/soec/soec.svg
=> Minor fix for initialization of SOEC

idaes/commands/wrap_solver_wsl.py, idaes/core/util/tests/test_utility_minimization.py, idaes/core/util/utility_minimization.py, idaes/generic_models/properties/core/phase_equil/tests/test_henry.py, idaes/generic_models/properties/core/reactions/tests/test_solubility_product_verification.py, idaes/generic_models/unit_models/skeleton_model.py, idaes/generic_models/unit_models/tests/test_skeleton_unit_model.py, idaes/power_generation/costing/tests/test_NGCC_costing.py
- run ` addheader -c .\addheader.yml`
=> Update some out of date copyright headers

docs/technical_specs/model_libraries/generic/unit_models/flash.rst, docs/user_guide/modeling_extensions/surrogate/alamopy/index.rst, docs/user_guide/modeling_extensions/surrogate/helmet/index.rst, docs/user_guide/modeling_extensions/surrogate/pysmo/pysmo_sampling_properties.rst, docs/user_guide/modeling_extensions/surrogate/ripe/index.rst, idaes/core/process_base.py, idaes/core/process_block.py
- Minor text edits for documentation files, closes #484 
- Fixed errors in a group of .rst files
- Fixed errors in two referenced .py scripts
=> Fix Documentation Typos

docs/technical_specs/core/util/index.rst, docs/technical_specs/core/util/tags.rst, idaes/core/util/__init__.py, idaes/core/util/tags.py, idaes/core/util/tests/test_tags.py
This adds a couple classes that let you tag quantities in a model for reporting output and setting input.  There are two purposes 1) easily identify important quantities in the complex model hierarchy and 2) allow a user to specify how the quantities should be displayed when writing to an SVG or table, or other report.
The is motivated by two things, I write similar features as a one-off in every flowsheet I put together for the PFD output, and I'm spending a lot of time searching all the time for the numbers I need.  Then when I hand off the model, it's hard to describe to someone what the key variables are.   I hope that this will simplify things. 
1. I agree my contributions are …
=> Add tag classes

idaes/core/util/tables.py, idaes/core/util/tags.py
1.)  Fixes a tag issue displaying variables that don't have values
2.)  In tables, in the function to get a state block for an arc, if the fist port doesn't have a state block try the second before giving up. 
=> Fix minor tag and tables issues.

idaes/core/util/tags.py, idaes/core/util/tests/test_tags.py, idaes/power_generation/costing/power_plant_costing.py, idaes/power_generation/flowsheets/soec/soec.py, idaes/power_generation/flowsheets/soec/soec_costing.py
Add some stuff to tabulate results
=> Add some stuff to tabulate results (NGCC branch)

idaes/power_generation/carbon_capture/mea_solvent_system/properties/vapor_prop.py, idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/column.py, idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/tests/test_column.py
=> Improving column model tests

idaes/power_generation/costing/power_plant_costing.py
This PR is intended to allow costing of the CO2 capture system at capture rates above 90% (between 90% - 97.7%).
- Two new dictionaries containing custom costing exponents and parameters have been added to power_plant_costing.py.
- The dictionaries were populated with values needed to cost the CO2 capture system above 90%.
- `get_PP_costing()` was modified to search for parameter values in the new custom dictionaries if it cannot find the data in the existing dictionaries loaded from the json files.
2. I represent I am authorized to make the …
=> added capital cost scaling support for 97% carbon capture

codecov.yml
This PR should take care of temporary inconsistencies in the reports that Codecov generates when a PR is updated, resulting in e.g. unrelated files being flagged as having coverage changes because of coverage data being submitted to Codecov at different times (because tests take longer to run on Windows). …
=> Configure Codecov to improve when report updates are created

idaes/commands/tests/test_commands.py, requirements-dev.txt, setup.py
=> Address test failures from #633

docs/getting_started/binaries.rst
Updates to wsl and petsc intallation guide.
-
-
=> Updates to wsl and petsc intallation guide

setup.py
- Add requirement `ipython<8.0.0`
=> Pin IPython version to address test failures (#661)

docs/getting_started/binaries.rst, idaes/config.py, idaes/core/solvers/tests/test_petsc.py
This fixes the Bonmin link, removes an extra test, and bumps the binary version to get a few minor PETSc fixes.
=> Fix link, test, and update binaries version

docs/index.rst, docs/static/css/custom.css
- Rewrite and organize displayed table of contents on index page
- Reorganize index page contents
=> Restyle & reorganize main index page

idaes/surrogate/pysmo/radial_basis_function.py
- Specify full option name for pandas option key (`precision` -> `display.precision`)
=> Address pandas 1.4.0 errors

idaes/surrogate/sampling/scaling.py, idaes/surrogate/sampling/tests/test_scaling.py
- Added a static method to create a scaling object based on 0->1 normalization.
-
-
=> Adding normalizing scaler constructor

idaes/power_generation/unit_models/feedwater_heater_0D_dynamic.py, idaes/power_generation/unit_models/helm/turbine_multistage.py
copy_port_value -> propagate_state (copy_port_values is deprecated)
=> Remove deprecated copy_port_values

idaes/power_generation/unit_models/helm/turbine_multistage.py
Add unit of measure to the multistage steam turbine power.
=> Add missing unit of measure

README.md
The lack of funding acknowledgement
Suggested by David Miller, to use this acknowledgement
- Extra section in the README.md file
-
=> Adding funding acknowledgement to README.md

idaes/dmf/tests/test_util.py, idaes/generic_models/properties/core/eos/tests/test_ceos_PR.py
- Adds value() method to resolve failing assertion tests
-
-
=> Insert value() method to resolve Boolean assertion error

idaes/ui/flowsheet.py, idaes/ui/fsvis/static/css/main.css, idaes/ui/fsvis/static/js/main.js, idaes/ui/fsvis/static/js/paper.js, idaes/ui/fsvis/static/js/stream_table.js, idaes/ui/tests/demo_flowsheet.json, idaes/ui/tests/flash_flowsheet.json, idaes/ui/tests/serialized_boiler_flowsheet.json
Potential user showed interest in marking links when they hover over streams in the stream table and vice versa.
-
-
=> Stream table brushing

idaes/generic_models/unit_models/column_models/solvent_column.py
- Unit of convective heat flow corrected
- Convective and total inter phase heat transfer equations corrected
Corrections have been made to the heat transfer equations in the solvent column model. This is expected to improve robustness.
- Using average liquid and vapor phase temperatures in the convective heat transfer equation
- Using the appropriate sign conventions and phase properties for calculating the total rate of heat transfer …
=> Solvent column corrections

idaes/ui/fsvis/static/css/bootstrap/bootstrap.css, idaes/ui/fsvis/static/css/main.css, idaes/ui/fsvis/static/js/paper.js, idaes/ui/fsvis/static/js/stream_table.js, idaes/ui/fsvis/templates/index.html
Adds the capability to turn off the stream brushing/highlighting feature
-
-
=> Adding a toggle feature to turn off the stream brushing

idaes/apps/uncertainty_propagation/tests/test_uncertainties.py, idaes/apps/uncertainty_propagation/uncertainties.py, setup.py
Bump the Pyomo tag to the 6.3.0 release.
=> Bump the Pyomo tag to the Pyomo 6.3 release

idaes/power_generation/flowsheets/rsofc/properties/natural_gas_PR_scaled_units.py, idaes/power_generation/flowsheets/rsofc/rsofc_costing.py, idaes/power_generation/flowsheets/rsofc/rsofc_module.py, idaes/power_generation/flowsheets/rsofc/rsofc_soec_flowsheet.py, idaes/power_generation/flowsheets/rsofc/rsofc_sofc_flowsheet.py
Updated soec flowsheet to use equivalent sofc stack values of number of cells (3.455e6) and area per cell (550 cm2). All results including costing and optimization were also updated
-
-
=> rSOFC - SOEC mode update

idaes/generic_models/properties/core/eos/tests/test_ceos_CO2_H2O.py, idaes/generic_models/properties/core/generic/generic_property.py, idaes/power_generation/properties/natural_gas_PR.py
- Adds step to activate missing constraint during phase equilibrium initialization step
- Adds step to fix and unfix temperature for enthalpy based property packages for phase equilibrium stem
- Fixes poorly written tests for one property package example
=> Fix bugs in modular properties initialization

idaes/core/util/model_serializer.py
It's a good thing I'm not a surgeon.  I left behind a couple print() statements. 
=> Remove left over print statments

idaes/core/ui/flowsheet.py, idaes/core/ui/fsvis/model_server.py, idaes/core/ui/fsvis/static/js/main.js, idaes/core/ui/fsvis/static/js/stream_table.js, idaes/core/ui/fsvis/static/js/toolbar.js, idaes/core/ui/fsvis/tests/test_model_server.py
Closes #838 
The server response from the PUT request to save the model isn't the appropriate response. That's why we're seeing these errors reported in #838 
-
-
=> Fix ajax response when a PUT /fs request is called to save a model

setup.py
Update the Pyomo tag to pull in some recent changes needed for #922 
- Update the Pyomo tag to be current with the main branch of Pyomo (as of 7/27/2022)
=> Update Pyomo tag

setup.py
This updates the IDAES Pyomo requirement to the final 6.4.2 release
-
-
=> Updating Pyomo to the 6.4.2 release

idaes/conftest.py
=> Fixing issue with pytest flags

idaes/tests/prescient/test_prescient.py, setup.py
=> Address test failures due to pandas 1.5

.github/actions/run-examples/action.yml
- CI failures in unrelated PRs such as e.g. #950
-
-
=> Update run-examples CI action to track changes in examples installation

idaes/core/util/performance.py, idaes/models_extra/column_models/tests/test_MEAsolvent_column.py, idaes/models_extra/column_models/tests/test_tray_column.py, idaes/models_extra/gas_solid_contactors/unit_models/tests/test_FB1D.py
This PR adds some additional models to the performance testing suite
- Performance tests for 1D Fixed Bed reactor model
- Performance tests for MEA solvent absorption column
- Performance tests for Tray Distillation Column model
=> Adding more models to performance testing suite

idaes/models_extra/power_generation/flowsheets/supercritical_power_plant/boiler_subflowsheet_build.py, idaes/models_extra/power_generation/flowsheets/supercritical_steam_cycle/supercritical_steam_cycle.py, idaes/models_extra/power_generation/flowsheets/test/test_scsc.py
Adjust flowsheet supercritical flowsheets for new display variable names. 
=> Fix supercritical pfd output

idaes/models_extra/power_generation/flowsheets/supercritical_steam_cycle/supercritical_steam_cycle.py
Fix mix up between file path string and sig string.
=> Fix supercritical_steam_cycle PFD output

setup.py
DO NOT MERGE
Opening this to check IDAES tests against Pyomo main before we cut the 6.4.3 release
-
-
=> Updating Pyomo in preparation for the 6.4.3 release

.github/workflows/v1-compat.yml, idaes/__init__.py, idaes/models_extra/carbon_capture/co2_compressor.py
=> Add support for optional activation of v1 compatibility mode

idaes/core/util/model_statistics.py, idaes/core/util/tests/test_model_statistics.py
This PR adds new utility functions for finding the set of variables which do not appear in any constraint in a model.
- `variables_not_in_activated_constraints_set`
- `number_variables_not_in_activated_constraints_set`
=> Function to find unused variables

docs/tutorials/advanced_install/index.rst
=> Change update step for advanced install instructions

idaes/core/util/model_serializer.py
=> Fix a lot of spelling mistakes

docs/explanations/modeling_extensions/diagnostics/index.rst
- Edits to documentation (one file)
=> Updated text in Degeneracy Hunter documentation.

idaes/core/util/expr_doc.py, setup.py
- Remove dependencies towards our ALARA (As Low As Reasonably Achievable) goal
Remove dependencies belonging to the following categories:
=> Spring cleaning for dependencies, Pt. 1: The Tree-Shaking

docs/explanations/modeling_extensions/matopt/index.rst, idaes/apps/matopt/README.md
Update publications in readme.md and index.rst
-
-
=> Minor documentation update for matopt

idaes/core/surrogate/pysmo/tests/test_polynomial_regression.py, setup.py
=> Fix Pandas.Series append

setup.py
Update Pyomo requirement after 6.6.1 release
=> Update pyomo requirement to 6.6.1

scripts/colab_helper.py
- Fix the URL to download the script (one line change)
=> Fix URL in colab_helper.py

idaes/core/base/tests/test_var_like_expression.py, idaes/core/base/var_like_expression.py, idaes/models/properties/modular_properties/eos/tests/test_enrtl.py, idaes/models/properties/modular_properties/eos/tests/test_ideal.py, idaes/models/properties/modular_properties/phase_equil/tests/test_henry.py, idaes/models/unit_models/tests/test_mscontactor.py, setup.py
Update Pyomo requirement to 6.6.2
=> Update the Pyomo tag to the 6.6.2 release

idaes/models_extra/power_generation/costing/power_plant_capcost.py
=> Fix typos being detected after CI check update

setup.py
Update Pyomo requirement to 6.7.0
=> Update the Pyomo tag to the 6.7.0 release

docs/reference_guides/model_libraries/generic/unit_models/mscontactor.rst, idaes/models/unit_models/mscontactor.py, idaes/models/unit_models/tests/test_mscontactor.py
This add support for dynamics to the MS Contactor model.
- Add method to construct volume and volume fraction terms.
- Add phase fractions to handle multiphase streams
- Added code to construct holdup and accumulation terms as required
- Added accumulation terms to balance equations
- Added units to 0 term in balances for steady-state cases
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission …
=> Add support for dynamics to MS Contactor

idaes/core/util/utility_minimization.py
=> Fix misspellings detected by typos v1.17

CITATION.cff, docs/index.rst
It is a good practice these days to include a preferred citation to software (whether a paper, book, software-specific DOI, etc.) to encourage acknowledgement and recognition of software in research. This PR adds a `CITATION.rff` file to the repository which creates a "Cite this repository" option on the right-hand side and adds a "Citing IDAES" section to the ReadTheDocs index.
- (See above)
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these …
=> Add preferred IDAES citation

.github/workflows/core.yml, .github/workflows/integration.yml
The existing GitHub Action workflows return deprecation warnings for the current versions of several different marketplace actions.
- Update appropriate actions to newest versions
=> Update Action Versions to address Node.js deprecation

docs/explanations/components/property_package/general/pure/Perrys.rst
=> Fixing parameter names in Perry.rst

CITATION.cff, README.md, docs/explanations/faq.rst, docs/explanations/model_diagnostics/degeneracy_hunter.rst, docs/explanations/model_diagnostics/svd_analysis.rst, docs/index.rst
This PR improves our FAQ page by adding some more answers for common questions, as well as adding more links to the IDAES discussion boards. It also updates our citation advice to include links to OSTI's archive of IDAES reelases.
-
-
=> Updating FAQs

.github/actions/setup-idaes/action.yml
=> Pin ampl-module-scip version to 20240121

setup.py
Update Pyomo requirement to 6.7.2.
-
-
=> Update the Pyomo tag to the 6.7.2 release

setup.py
- Update pyomo requirement to 6.7.3 following today's Pyomo release
=> Update pyomo requirement to 6.7.3

.github/CODEOWNERS, .github/workflows/core.yml, .github/workflows/typos.toml, idaes/core/initialization/tests/test_initializer_base.py
=> Pin typos version to latest currently available tag v1.24.5

README.md
This is the world's smallest / least relevant PR, but I noticed that the Downloads badge wasn't rendering in the README.
- Fix URL for Download badge
=> New URL for Downloads Badge

setup.py
Bumping the Pyomo tag to check for issues with the 6.9.1 patch release.
-
-
=> Update Pyomo to the 6.9.1 release

idaes/core/initialization/block_triangularization.py, idaes/core/initialization/general_hierarchical.py, idaes/models/properties/modular_properties/base/generic_property.py, idaes/models/properties/modular_properties/base/tests/test_generic_property.py, idaes/models/properties/modular_properties/base/tests/test_generic_reaction.py, idaes/models/properties/modular_properties/coolprop/tests/test_coolprop_wrapper.py, idaes/models/properties/modular_properties/state_definitions/electrolyte_states.py, idaes/models/unit_models/heat_exchanger_ntu.py, idaes/models/unit_models/tests/test_heat_exchanger.py, idaes/models_extra/column_models/MEAsolvent_column.py, idaes/models_extra/column_models/enhancement_factor_model_pseudo_second_order_explicit.py, idaes/models_extra/column_models/properties/MEA_solvent.py, idaes/models_extra/column_models/solvent_column.py, idaes/models_extra/column_models/solvent_condenser.py, idaes/models_extra/column_models/tests/test_MEAsolvent_column.py, idaes/models_extra/column_models/tests/test_solvent_condenser.py
It's finally time to get the (mostly) fixed MEA column into IDAES.
- MEA column tests pass again
- Better initialization and scaling for electrolytes
- Minor fixes in NTU heat exchanger and condenser model
=> MEA Column Fix
