IDAES/idaes-pse

- .circleci/config.yml
- README.md
- docs/advanced_user_guide/advanced_install/index.rst
- docs/advanced_user_guide/advanced_install/terms_commands.rst
- docs/advanced_user_guide/developer/codereview.rst
- docs/advanced_user_guide/developer/devsw.rst
- docs/conf.py
- docs/user_guide/modeling_extensions/matopt/index.rst
- idaes/apps/matopt/README.md
**NOTE:** When this PR is approved, you *must* do the following so it can be merged:
* Add the "approved" tag to the pull-request
* Trigger tests by pushing a commit or manually re-running in CircleCI
See [this wiki page](https://github.com/IDAES/idaes-dev/wiki/Github-Pull-Request-Workflow-with-Approval-Tag) for details.
----
Misc breakages caused by renaming the default branch to `main`
- Align to updated GitHub convention of naming the default branch `main`
Change references to `master` to use `main` instead for:
- Tools (e.g. CircleCI)
- Documentation
1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this …
> Rename "master" to "main"

- idaes/generic_models/unit_models/cstr.py
**NOTE:** When this PR is approved, you *must* do the following so it can be merged:
* Add the "approved" tag to the pull-request
* Trigger tests by pushing a commit or manually re-running in CircleCI
See [this wiki page](https://github.com/IDAES/idaes-dev/wiki/Github-Pull-Request-Workflow-with-Approval-Tag) for details.
----
A bug was found where the wrong argument from the config block was being used in creating the material balance constraints for the CSTR model (affected cases with chemical equilibrium).
This is a re-creation of PR #45 to address some lingering issues with the switch to the open repository.
-
-
1. I agree my contributions are submitted under the license terms …
> Re-creating PR To fix CSTR configuration bug

- idaes/generic_models/properties/core/state_definitions/FPhx.py
- idaes/generic_models/properties/core/state_definitions/FTPx.py
- idaes/generic_models/properties/core/state_definitions/FcPh.py
- idaes/generic_models/properties/core/state_definitions/FcTP.py
- idaes/generic_models/properties/core/state_definitions/FpcTP.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FPhx.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FTPx.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FcPh.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FcTP.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP.py
A couple of people have noted that the generic properties framework does not inform the user if they mis-type an entry in the `state_bounds` configuration dict. This PR adds checks for unexpected keys and raises a `ConfigurationError` if one is found (or  logs a warning in the case of mole fractions if they are a state variable).
-
- …
> Adding checks on state_bounds argument to find unexpected keys

- idaes/core/components.py
- idaes/generic_models/properties/core/eos/ceos.py
- idaes/generic_models/properties/core/eos/ideal.py
- idaes/generic_models/properties/core/generic/generic_property.py
Support for calculating specific heat capacities was missing from the generic property framework.
-
-
> Adding support for cp calculations to generic property framework

- docs/user_guide/components/property_package/general/pure/NIST.rst
- docs/user_guide/components/property_package/general/pure/Perrys.rst
- docs/user_guide/components/property_package/general/pure/RPP.rst
- docs/user_guide/components/property_package/general/pure/RPP3.rst
The units of measurement specified in the docs for the generic property package are incorrect for heats and entropies of formation. The docs state specific units (generally SI), whereas the actual parameters are specified in units consistent with the base units specified for the property package.
- Correct units in docs
- Add a few clarifying comments, notably about the F and H parameters in the NIST Shomate equation.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property …
> Correcting units of measurement in docs

- .github/workflows/core.yml
- .github/workflows/integration.yml
Hotfix for #168 because only job names (and not workflow names) seem to count as check names for populating the branch protection rules menu.
> Modify name of pytest job in integration workflow

- .github/workflows/integration.yml
Once #171 was merged, I realized that the integration tests were being triggered by every label being added to the PR, as opposed to the intended behavior of skipping the run unless the added label was the correct one. This was due to the wrong field of the `github.event` object being used in the condition. The fix in this PR has been tested on the branches in my fork of `idaes-pse` that I'm using to test changes to the CI configuration before deploying them here,
2. I represent I am authorized to make the contributions and grant the license. If my …
> GitHub Actions CI hotfix: use correct field for integration workflow trigger on PRs

- .github/actions/display-debug-info/action.yml
- .github/workflows/core.yml
- .github/workflows/integration.yml
- Use dedicated actions to display debug info consistently and without causing errors due to shell escaping issues that would occur with the previous strategy
Testing problematic characters: it's this one, `maybe_this_one_too`.
> Fix shell escaping issues in GitHub Actions workflows

- codecov.yml
Spurious fluctuations in coverage reports cause the Codecov `project` status check (which can be, and often is, completely unrelated to a particular PR's changes) to report a negative coverage delta, resulting in the entire PR to be flagged as failing the checks. This is because the default behavior is to use a threshold of 0 to classify a coverage report. 
- Increase the accepted threshold to 1% for the `project` check
- Specify a tolerance of 0% for the `patch` check, which is limited to the files changed in the PR.
2. I represent I am authorized …
> Avoid false positive in project coverage status checks

- idaes/generic_models/properties/core/examples/reactions/reaction_example.py
In demonstrating the generic reaction framework to a user, it was discovered that the associated thermophsyical parameter block was missing methods for defining the specific molar enthalpy, and thus that it could not be used in an example with an actual reactor model. This PR adds the necessary property methods and parameters to the thermo package so that the example can be coupled with a CSTR if desired.
- Adds methods and parameters to example thermophysical parameter configuration dict.
-
2. I represent I am authorized to make the contributions …
> Improve example for Generic Reaction Framework

- idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
- idaes/generic_models/properties/core/generic/generic_property.py
In support of the NAWI project, support for molar concentrations is required for use in reactions that are written in concentration form.
- Add methods for calculating molar concentrations (both average and by phase)
- Add a couple of simple tests for new methods.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that …
> Adding support for molarity to generic properties

- idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_Ideal_VLE.py
- idaes/generic_models/properties/core/generic/generic_reaction.py
Development in NAWI identified a misnamed variable in the generic reaction framework.
- Fixed misnaming.
- Also fixed a interdependency in a test.
> Fixing misnamed variable in generic reactions

- idaes/generic_models/properties/core/examples/tests/test_ASU_PR.py
- idaes/generic_models/properties/core/examples/tests/test_ASU_PR_Dowling_2015.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcTP.py
- idaes/generic_models/properties/core/examples/tests/test_BT_PR.py
- idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_Ideal_VLE.py
- idaes/generic_models/properties/core/examples/tests/test_CO2_bmimPF6_PR.py
- idaes/generic_models/properties/core/examples/tests/test_HC_PR.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FPhx.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FTPx.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FcPh.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FcTP.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP.py
Currently, testing of some core aspects of the generic properties framework is being done in the examples tests rathe than tests of the actual components responsible for creating the required features. This is not good for multiple reasons, not least being that making otherwise simple changes in these core components results in multiple example tests failing which then need to be fixed.
This PR reorganizes the tests so that these core features are tested in the tests for the associated components rather than in the examples.
- Move all testing of components and methods created by the state definition classes to the tests for those modules, and removing them from the examples tests.
- Removing some redundant pytest mark` that should be deprecated.
- Linting of some affected some files.
By …
> Reorganising tests of generic properties

- .github/actions/setup-idaes/action.yml
- .github/workflows/core.yml
- .github/workflows/integration.yml
- docs/technical_specs/model_libraries/generic/property_models/swco2.rst
- docs/technical_specs/model_libraries/power_generation/unit_models/turbine_inlet.rst
- docs/technical_specs/model_libraries/power_generation/unit_models/turbine_outlet.rst
- setup.py
- Installation errors preventing Pyomo version 6 and up from being installed
- Remove installation constraints requiring `pyomo<6` in `setup.py`
- Add `pytest-dev` job using dev dependencies (`requirements-dev.txt`) and Python 3.9
- This uses a separate test job matrix without coverage report, and with "experimental mode", i.e. settings to prevent the entire workflow to be marked as failed if any job fails
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes …
> Enable newer Pyomo version in setup.py

- .github/workflows/util-cleanup.yml
- Because of security contraints built into GitHub Actions, there is no direct way to manually dispatch a workflow so that it runs on a PR branch coming from a fork of the main repository
- To work around this limitation without bypassing the security measures, one of the event types allowed for PRs can be used as a makeshift trigger, as long as the workflow is set up to include this event type among its triggers
- An example of this is the integration tests workflow, that is set up to trigger when a specific label is added to the PR
- This current approach works, but has a few shortcomings:
- The actual triggering event is emitted when the label is added, so if the trigger label is already present on the PR, it must be removed and then added again, which is cumbersome and not very …
> Add utility workflow to remove labels used to trigger CI workflows

- .github/actions/check-pr-approval/action.yml
- .github/workflows/integration.yml
- Currently, running integration tests on a PR requires manually adding a label to the PR, which is cumbersome and not intuitive
- This PR enables integration tests to be dispatched automatically for approved PRs
- More specifically, integration tests will run:
- As soon as the second approving review is submitted on a PR
- When a commit is pushed to the branch of an approved PR without affecting the reviewed code (this is common when merging back changes from `main`, which required repetitive manual intervention)
- (same as before) When the target branch is not a PR (e.g. when integration tests are run on the `main` branch as part of nightlies)
- (same as before) When a special trigger label is added on a PR
- This functionality is being kept, even though the vast majority of cases …
> Enable integration tests to run automatically on approved PRs

- docs/user_guide/modeling_extensions/matopt/index.rst
- idaes/apps/matopt/README.md
- idaes/apps/matopt/materials/__init__.py
- idaes/apps/matopt/materials/canvas.py
- idaes/apps/matopt/materials/geometry.py
- idaes/apps/matopt/materials/lattices/__init__.py
- idaes/apps/matopt/materials/lattices/cubic_lattice.py
- idaes/apps/matopt/materials/lattices/diamond_lattice.py
- idaes/apps/matopt/materials/lattices/fcc_lattice.py
- idaes/apps/matopt/materials/lattices/lattice.py
- idaes/apps/matopt/materials/lattices/perovskite_lattice.py
- idaes/apps/matopt/materials/lattices/unit_cell_lattice.py
- idaes/apps/matopt/materials/lattices/wurtzite_lattice.py
- idaes/apps/matopt/materials/tiling.py
- idaes/apps/matopt/tests/test_matopt_objects_construction.py
- idaes/apps/matopt/tests/test_matopt_objects_functionality.py
- idaes/apps/matopt/util/util.py
N/A
We have developed new objects and capabilities of MatOpt for designing semiconductor nanowire materials. This PR is the code contribution as promised in the IDAES FWP. We have tested the code and examples in the example-pse repository locally. There are some unit tests for constructing new objects in the tests subfolder. We will also provide an example illustrating designing nanowires via a PR to the example-pse repository soon.
- New `LinearTiling` class for 1d periodicity
- New `Cylinder` and `CylindricalSector` classes for the shape of the design canvas
- New `DiamondLattice` and `WurtziteLattice` classes to support a broader range of materials
- New capability of `Canvas` class to return n-th layer neighbor indices
- Modification of `util.myArrayEq` function for faster geometric …
> Matopt upgrade

- docs/getting_started/index.rst
- Now that a Conda package is available for `idaes-pse`, add instructions on how to install it to the general installation docs (issue #233)
- Add "Install IDAES using Conda" section to installation docs
> Add section on installing IDAES using Conda to installation docs

- idaes/core/util/misc.py
- idaes/core/util/tests/test_misc.py
This makes it possible to specify an arc for the ```copy_port_values()``` function.  Just saves some typing and make it a little easier to use.  It still works the way it did, just provides an extra option. 
> Minor update to copy_port_values(), now can take and arc

- idaes/util/tests/test_download_bin.py
Mark bin download test as integration.  That makes it run less often and random network-type errors that causes the download to fail will happen less often.
> Mark bin download test as integration

- idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/tests/test_column.py
- idaes/power_generation/flowsheets/test/test_NGFC.py
- idaes/power_generation/properties/tests/test_SOFC_ROM.py
Changing the pytest marks on some slow tests to `integration` to speed up running of common tests.
-
-
> Moving some slow tests to integration

- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
- idaes/generic_models/properties/core/state_definitions/FcPh.py
- idaes/generic_models/properties/core/state_definitions/FpcTP.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FcPh.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FcPh_electrolyte.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP_electrolyte.py
This should be the final PR in this batch of changes, adding support for the last of the current state definitions in electrolyte systems.
As @TimBartholomew noted, the test for all of these look very similar, but there are enough differences to make it more effort than I want to go to to come up with a standard form for them.
- FpcTP and FcPh forms for electrolyte systems
-
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I …
> Adding support for more state definitions with electrolytes

- docs/technical_specs/model_libraries/generic/unit_models/pressure_changer.rst
- idaes/generic_models/unit_models/pressure_changer.py
- idaes/generic_models/unit_models/tests/test_pressure_changer.py
Adding some support for performance curves in pressure changers.  Need these for gas turbines among other things.  This seems to work, but we can have some discussion around the design of it.  The main reason I used a sub-block for performance curves is that I didn't put any restriction on the form of the performance curves, so it gives me an easy way to deactivate and activate them.  The bad thing about it is that the variables and expressions that go into the performance cruves are defined in the parent block, so writing the performance curves is a little convoluted.  I can add some docs if everyone agrees to the implementation.  There are two ways to add curves, as seen in the tests.  Either a callback or just adding constraints after constructing the pressure changer.  Either way ends …
> Add performace curve structure to isentropic pressure changers.

- docs/user_guide/components/property_package/general/pure/NIST.rst
The documentation for calculating specific enthalpy using the NIST Shomate equation was not updated when fixing the bugs in PR #223.
- Removed `t_ref` from Shomate equation in docs
-
> Correcting equation in documentation

- docs/user_guide/components/property_package/general_reactions/equil_constant.rst
- docs/user_guide/components/property_package/general_reactions/equil_form.rst
- idaes/generic_models/properties/core/eos/ideal.py
- idaes/generic_models/properties/core/generic/generic_property.py
- idaes/generic_models/properties/core/reactions/equilibrium_constant.py
- idaes/generic_models/properties/core/reactions/equilibrium_forms.py
- idaes/generic_models/properties/core/reactions/tests/test_equilibrium_constant.py
- idaes/generic_models/properties/core/state_definitions/FPhx.py
- idaes/generic_models/properties/core/state_definitions/FTPx.py
- idaes/generic_models/properties/core/state_definitions/FcPh.py
- idaes/generic_models/properties/core/state_definitions/FcTP.py
- idaes/generic_models/properties/core/state_definitions/FpcTP.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FPhx_electrolyte.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FTPx_electrolyte.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FcPh_electrolyte.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FcTP_electrolyte.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP_electrolyte.py
This is hopefully the final step in getting electrolytes working properly. This PR introduces a helper function for equations of state and other property methods tp get the correct `mole_frac_phase_comp` object depending on whether electrolytes are in use or not.
This method assume that if the system is using electrolytes that the correct `mole_frac_phase_comp` to use is that for the true species list. In short - if your are bothering to calculate true species compositions for an electrolyte system, you probably want to be using these to calculate the thermophysical properties of the system. Otherwise, why would you bother?
- Adds helper method for getting correct `mole_frac_phase_comp` component.
- Updated `Ideal`  EoS to use the new helper method and adds flag to indicate support for …
> Final (hopefully) steps in setting up infrastructure for electrolytes

- docs/user_guide/components/property_package/general_reactions/equil_constant.rst
- idaes/generic_models/properties/core/reactions/equilibrium_constant.py
- idaes/generic_models/properties/core/reactions/tests/test_equilibrium_constant.py
When using the Gibbs energy form to calculate equilibrium constants, by convention the units of Keq are (mol/L)^order. This was not captured correctly in the origin implementation.
- Limit the use of `gibbs_energy` method to reactions using molarity or activity basis
- Add unit conversion to convert (mol/L)^order to the base system of units.
- Document limitations of `gibbs_energy` implementation.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these …
> Fixing unit consistency issue in Gibbs Energy form for Keq

- idaes/core/components.py
- idaes/core/control_volume0d.py
- idaes/core/control_volume1d.py
- idaes/core/tests/test_components.py
- idaes/core/unit_model.py
- idaes/generic_models/properties/core/eos/ideal.py
- idaes/generic_models/properties/core/eos/tests/test_ideal.py
- idaes/generic_models/properties/core/phase_equil/forms.py
- idaes/generic_models/properties/core/pure/RPP5.py
- idaes/generic_models/properties/core/reactions/dh_rxn.py
- idaes/generic_models/properties/core/reactions/equilibrium_constant.py
- idaes/generic_models/properties/core/reactions/tests/test_equilibrium_constant.py
This PR addresses 4 bugs identified recently.
1. Generic Reactions: Gibbs energy and van 't Hoff forms of calculating equilibrium constants could not be combined.
2. Generic Properties: Scaling tools raised an `Exception` due to trying to create fugacity expressions for non-vapourisable components.
3. Generic Properties: RPP5 library had misnamed variable when checking for prior parameter creation resulting in implicit replacement of parameters.
4. Unit model: `add_state_material_balances` had indexing issues due to not checking for non-vapourisables and non-condensables.
- Reworked Gibbs energy form to not build its own `dh_rxn`
- Added new option to component declaration to indicate that a component does not have a vapour pressure and can thus be skipped when calculating frugalities. …
> 4 bug fixes

- idaes/generic_models/properties/core/generic/generic_property.py
A bug was identified in the generic property framework that caused species which should not be present in a given phase to be inadvertently added to the phase-component set. This bug was only present when using the electrolyte extension.
- Fixed incorrect indentation so that species in non-aqueous phases do not get added to `true_phase_component_set`.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received …
> Fixing bug with creating phase-component set in Generic Properties

- idaes/config.py
This bumps the binary version.  There is no need for people to update now.  Here are the changes
1. As requested by Pyomo team, the solver executables are statically linked with the ipopt libraries.
2. The possibility of missing zlib1.dll on Windows is fixed.
3. Added a test external function for testing string args and variable length argument lists.  This is for https://github.com/Pyomo/pyomo/pull/1904.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes …
> Bump bin version

- idaes/generic_models/properties/core/reactions/equilibrium_constant.py
This PR fixes an issue with units in the module `equilibrium_constant.py` method `def calculate_scaling_factors(b, rblock)`.
The method was lacking conversion of units causing the scaling factors to be off by several orders of magnitude resulting in numerical issues.
- The line `rblock._keq_units` was added to fix this issue …
> Fixing issue with units in the equilibrium_constant module

- idaes/generic_models/properties/core/eos/ceos.py
- idaes/generic_models/properties/core/generic/generic_property.py
Cleans up a missing check for non-vapourisable and non-condensable components, plus updating to the new API for indexing sets.
-
-
> Fixing some issues with indexing sets in generic properties

- .github/actions/pylint/action.yml
- .github/actions/setup-idaes/action.yml
- README.md
- docs/advanced_user_guide/advanced_install/index.rst
- docs/getting_started/index.rst
- idaes/apps/uncertainty_propagation/tests/test_uncertainties.py
- idaes/config.py
- idaes/dmf/tests/util.py
- idaes/surrogate/pysmo/tests/test_kriging.py
- idaes/surrogate/pysmo/tests/test_polynomial_regression.py
- idaes/surrogate/pysmo/tests/test_radial_basis_function.py
- requirements-dev.txt
- requirements.txt
- setup.py
- Move dependencies needed to install a prerelease version of IDAES to `setup.py` so that it can be installed without having to clone the repository
- Streamline installation process by reducing number of recommended installation workflows to two (for **users** and **developers**)
- Update `setup.py` defining a `[prerelease]` optional tag (`extras_require`) for `pip install` containing the appropriate versions of Pyomo ~~(and, following #249, currently also PySP)~~
- Move developer dependencies to `requirements-dev.txt`
- Remove unnecessary dependencies (e.g. `mock` which is part of the Python stdlib as `unittest.mock`)
- Update documentation accordingly
- `C1`: Persons who need to install IDAES are divided in **2 categories**, depending on whether they **need to access the source code** …
> Refactor setup.py and requirements-dev.txt to streamline installation workflows

- idaes/__init__.py
- idaes/config.py
- idaes/core/solvers.py
- idaes/core/util/tests/test_homotopy.py
- idaes/tests/test_config.py
- idaes/tests/test_ipopt.py
This adds a context manager that allows you to temporarily change the IDAES config and have it revert back after the with-block.  This is mainly for testing.  Config changes for one test can affect others.  For example, you may want to set ipopt to default to user scaling, so all the initialization routines use it.  But that setting will stick around for subsequent tests potentially breaking them.  So the idea is that you can use the new context manager to make sure tests don't make lasting changes to the config.
This also makes some changes so the pointer to the IDAES ConfigDict is only in one place. 
1. I agree my contributions are submitted under the license terms described in …
> Context manager for temprary config changes

- idaes/core/util/model_statistics.py
- idaes/core/util/tests/test_dyn_utils.py
- idaes/core/util/tests/test_misc.py
- idaes/core/util/tests/test_model_statistics.py
- idaes/core/util/tests/test_phase_equilibria.py
- idaes/generic_models/control/tests/test_steam_tank.py
- idaes/generic_models/properties/core/generic/tests/test_generic_property.py
- idaes/generic_models/properties/core/reactions/tests/test_rate_forms.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FPhx.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FTPx.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FcPh.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FcTP.py
- idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP.py
- idaes/generic_models/properties/examples/tests/test_saponification_thermo.py
- idaes/generic_models/properties/tests/test_iapws95.py
- idaes/generic_models/unit_models/tests/test_separator.py
This PR should fix all the issues relating to https://github.com/Pyomo/pyomo/pull/1954. This process also identified and fixed a number of tests that did not work as expected.
- Fix tests where `.value` or `value()` should have been used
- Fix a few tools which rely on values which ere not using `value()`
- Fix some tests for set membership that fail under Pyomo 6.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I …
> Updates for Pyomo 6 compatibility

- idaes/generic_models/unit_models/distillation/tests/test_conventional_tray.py
- idaes/generic_models/unit_models/distillation/tests/test_feed_tray.py
- idaes/generic_models/unit_models/distillation/tests/test_partial_condenser.py
- idaes/generic_models/unit_models/distillation/tests/test_reboiler.py
- idaes/generic_models/unit_models/distillation/tests/test_total_condenser.py
- idaes/generic_models/unit_models/distillation/tests/test_tray_column.py
- idaes/generic_models/unit_models/distillation/tests/test_tray_side_liq_draw.py
- idaes/generic_models/unit_models/distillation/tests/test_tray_side_vap_draw.py
As part of testing for issue #344, it was revealed that the distillation tests were marking some tests using solvers with the `unit` mark. This PR standardises the use of pytest marks in the distillation tests, cleans up some deprecated marks and adds unit consistency checks.
- Marks all tests involving a solver with the `component` mark
- To make the above work, moves setting of degrees of freedom to the fixture definition
- Removes older pytest marks that are no longer in use
- Adds unit consistency checks to all cases
2. I represent I am …
> Standardising distillation tests

- idaes/core/util/scaling.py
This improves the speed of the function for finding large and small Jacobian elements.  The previous version wasn't iterating through the sparse matrix properly, and wasting time. 
> Fix inefficient function for Jacobian elements

- docs/user_guide/logging.rst
- idaes/apps/caprese/nmpc.py
- idaes/apps/matopt/opt/mat_modeling.py
- idaes/core/plugins/simple_equality_eliminator.py
- idaes/core/plugins/variable_replace.py
- idaes/core/util/convergence/convergence_base.py
- idaes/core/util/convergence/tests/test_convergence.py
- idaes/core/util/misc.py
- idaes/generic_models/properties/core/examples/tests/test_ASU_PR.py
- idaes/generic_models/properties/core/examples/tests/test_ASU_PR_Dowling_2015.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcTP.py
- idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_Ideal_VLE.py
- idaes/generic_models/properties/core/examples/tests/test_CO2_bmimPF6_PR.py
- idaes/generic_models/properties/core/examples/tests/test_HC_PR.py
- idaes/generic_models/properties/core/examples/tests/test_HC_PR_vap.py
- idaes/logger.py
- idaes/surrogate/pysmo/tests/test_sampling_modified.py
- idaes/surrogate/pysmo/tests/test_utils.py
- idaes/util/update_workshop_materials.py
- scripts/workshops/update_workshop_materials.py
- setup.py
This is testing against the Pyomo 6.0 RC1
- Update Pyomo tag
- Remove PyUtilib dependency
> Updating pyomo to the 6.0.rc1 tag, removing PyUtilib dependency

- idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcTP.py
- idaes/generic_models/properties/core/examples/tests/test_HC_PR_vap.py
Whilst looking through some tests, I found some tests marked as `unit` which required solvers.
- Added correct pytest marks, and removed a few deprecated marks
- Move setting of degrees of freedom to fixtures in a few cases to support separation of unit and component tests.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of …
> Fixing some pytest marks

- docs/user_guide/configuration.rst
- idaes/__init__.py
- idaes/commands/__init__.py
- idaes/commands/base.py
- idaes/commands/config.py
- idaes/commands/convergence.py
- idaes/commands/examples.py
- idaes/commands/tests/test_commands.py
- idaes/config.py
Even though nobody asked for it, I put together a little utility for idaes configuration from the command line.   I also sped up the imports for the idaes command, so it doesn't run annoyingly slow.  @jsiirola I tried to move to pyomo ConfigBlocks as much as possible, but there is still a bit of an issue with logger configuration since loggers have periods in their names.  That means I have to use a dict there instead of a ConfigBlock, since ConfigBlock keys can't have periods (and I use logging.dictConfig() directly, in which keys may have periods).  @dangunter, I messed with your imports in get-examples to speed things up.  You'll probably want to take a look at that.  The main issue I had was figuring out how to mange setuptools.  I ended up just moving it in the command function call …
> Command line config tools

- idaes/config.py
Ubuntu 19.10 is past the end of it's life, and I can't keep the docker container I use to build it up-to-date anymore.  I think I can just point it to the 18.04 binaries, and everything will be fine, and I'll have less work.
> Use Ubuntu 18.04 binaries on all release from 18.04 to 19.10

- setup.py
Pyomo 6.0.0 logs some errors when running `solve(tee=True` within a Jupyter notebook.  The Pyomo team is preparing a 6.0.1 release (due out today); this PR tests IDAES/main against the RC1 for that release.
- Test IDAES against Pyomo 6.0.1 (rc1)
> Bumping the pyomo dependency to Pyomo 6.0.1 (rc1)

- idaes/power_generation/unit_models/helm/turbine_multistage.py
Seems I failed to consider that you may not have feedwater heaters and may not have extractions splits.  This fixes.
> Fix issue where there are no extraction splits

- idaes/generic_models/unit_models/separator.py
- idaes/generic_models/unit_models/tests/test_flash.py
- idaes/generic_models/unit_models/tests/test_separator.py
This is a problem reported by @minhwvu.  The scaling factor calculation is broken for separators when the separator doesn't have it's own mixed state block.  Unfortunate, I think we should try to get the fix in this release if possible.   I added a test that demonstrates the problem then fixed it.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required …
> Fix separator scale factor calcs

- idaes/core/property_base.py
- idaes/generic_models/properties/core/eos/enrtl.py
- idaes/generic_models/properties/core/eos/eos_base.py
- idaes/generic_models/properties/core/eos/ideal.py
- idaes/generic_models/properties/core/eos/tests/test_enrtl_verification_NaCl.py
- idaes/generic_models/properties/core/eos/tests/test_ideal.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
- idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_Ideal_VLE.py
- idaes/generic_models/properties/core/generic/generic_property.py
The PR make the Ideal property package the base class for the eNRTL model so that it has access to common ideal properties. This should make the eNRTL model usable in unit models, and non-ideal properties can be added gradually as they are developed.
This PR also corrects a bug in the Ideal property package where the pressure dependent term for enthalpy of incompressible materials was not included.
- Lots
- …
> Adding ideal properties to eNRTL model

- idaes/core/util/model_serializer.py
- idaes/core/util/tests/test_model_serializer.py
Fixes an issue where the root component name of the block or module doesn't match what's in the saved state.  Places where this root name mismatch occur is when you have models with different name, but the same structure, or when you have indexed blocks and want to copy the results for one block to other blocks.  This was possible to do before by providing the root name, but now it should just work automatically. …
> Fix model serializer root name issue

- idaes/generic_models/properties/core/eos/enrtl_reference_states.py
The Unsymmetric reference state for the eNRTL model is based on infinite-dilution of ionic species. Previously this was represented using zero mole fractions for ionic species, but this resulted in issues with raising 0 to fractional and negative powers.
- Changes the mole fractions of ionic species at the unsymmetric reference state to an EPS value rather than zero.
-
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that …
> Correcting unsymmetric reference state to be near-zero instead of zero

- setup.py
- `package_data` patterns need to be specified for any non-Python file that's needed at runtime
- Recent changes from `json` to `json.gz` and introducing `.dat` files caused some tests to break. To wit, these are:
- `idaes/power_generation/flowsheets/test/test_NGFC.py`
- `python -c 'from idaes.power_generation.flowsheets.NGFC.NGFC_flowsheet import main; main()'`
- Packaging issues are often hidden by the fact that most of our testing (both individually and in the CI checks) installs IDAES in developer mode (`pip install --editable`), while `package_data` is relevant within IDAES when using `pip install .`
- Add `package_data` glob patterns for gzipped JSON and DAT files
A proper check to detect such issues going forward is in the making. In the meanwhile, in the interest of getting this …
> Fix errors due to missing json.gz and dat files when installing IDAES not in editable mode

- idaes/core/flowsheet_model.py
- idaes/core/tests/test_flowsheet_model.py
Currently, there is some inconsistency in how the time domain is handled between top level and sub-flowsheets. Notably, `flowsheet.time` works for top-level flowsheets, but `flowsheet.config.time` is required for sub-flowsheets. This PR makes `time` a property of all `FlowsheetBlocks` so that `flowsheet.time` will work for all flowsheets.
- Make `time` a property of `FlowsheetBlocks`
- Store the time domain or a reference to in in `_time`
- Update `_setup_dynamics` to define the `_time` attribute.
2. I represent I am authorized to make the …
> Making time a property of flowsheets

- .github/actions/pylint/action.yml
- .pylint/idaes_transform.py
- requirements-dev.txt
- From experience in the past months, pylint checks are highly sensitive to changes made in pylint
- Having a pinned version allows us IDAES maintainers to review and possibly update it *in a proactive way*, as opposed to having to be *reactive* when a pylint update is released
- Conceptually, as we're using pylint to check for changes *within IDAES*, it makes sense to treat the pylint version as a "test constant"
- Pin pylint version in `requirements-dev.txt`
- Add version compatibility check to IDAES transform plugin
- The checks compares the pylint version used at runtime with a "reference version" defined in the plugin, and displays a warning if the two don't match (specifying that this is not necessarily a problem to reduce confusion/"warning fatigue" for the IDAES developer running …
> Pin pylint version used in CI checks to avoid unexpected check failures

- docs/user_guide/modeling_extensions/surrogate/pysmo/pysmo_kriging.rst
- docs/user_guide/modeling_extensions/surrogate/pysmo/pysmo_polyregression.rst
- docs/user_guide/modeling_extensions/surrogate/pysmo/pysmo_radialbasisfunctions.rst
- docs/user_guide/modeling_extensions/surrogate/pysmo/pysmo_sampling_properties.rst
#401 
The name of the file containing the surrogate tools was changed from "surrogates" to "surrogate" a while back - this PR seeks to correct the docs to reflect that.
- change `idaes.surrogates.pysmo` to ` idaes.surrogate.pysmo` in docs
> Fix typos in PySMO import statements (documentation)

- idaes/generic_models/unit_models/heat_exchanger_1D.py
- idaes/generic_models/unit_models/tests/test_heat_exchanger_1D.py
- Fixing linter errors
- Removing old pytest markers from `test_heat_exchanger_1D.py`
> HX1D: updting linter errors and removing old  pytest markers

- docs/technical_specs/model_libraries/generic/property_models/interrogator.rst
- idaes/core/components.py
- idaes/core/phases.py
- idaes/generic_models/properties/interrogator/properties_interrogator.py
- idaes/generic_models/properties/interrogator/reactions_interrogator.py
- idaes/generic_models/properties/interrogator/tests/test_properties_interrogator.py
- idaes/generic_models/properties/interrogator/tests/test_reactions_interrogator.py
A couple of short comings have been identified in the properties interrogator tools:
1. Tools do not work with Unit Models which define specific phase lists that are not ["Liq", "Vap"]
2. Interrogator tools need to be updated to use the Pyomo UnitsContainer
- Updates units in interrogator tools
- Adds ability for users to (manually) define custom phase and components sets
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent …
> Improvements to Properties Interrogator

- idaes/apps/caprese/common/config.py
Was using an Enum subclass for config arguments that has been deprecated. Have removed this class, replacing it with enum.Enum to get rid of deprecation warnings.
> Stop using deprecated ConfigEnum class in Caprese

- idaes/apps/uncertainty_propagation/tests/test_uncertainties.py
- idaes/conftest.py
- idaes/tests/test_headers.py
- idaes/tests/test_style.py
- idaes/tests/test_tests.py
All tests in the pytest test suite should have at least one of the required markers (`unit`, `component`, `integration`).
This PR implements this by adding a check that runs when the tests items are collected and causes any test without a required marker to fail.
- Add function in `conftest.py` to check that test items have required markers
- Refactor existing code running during `pytest_runtest_setup` for consistency
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property …
> Add check in pytest to enforce that tests have required markers

- idaes/core/components.py
- idaes/core/phases.py
- idaes/core/tests/test_phases.py
- idaes/generic_models/properties/core/eos/ceos.py
- idaes/generic_models/properties/core/eos/enrtl.py
- idaes/generic_models/properties/core/eos/eos_base.py
- idaes/generic_models/properties/core/eos/ideal.py
- idaes/generic_models/properties/core/eos/tests/test_ceos_PR.py
- idaes/generic_models/properties/core/eos/tests/test_enrtl.py
- idaes/generic_models/properties/core/eos/tests/test_enrtl_verification_NaCl.py
- idaes/generic_models/properties/core/eos/tests/test_ideal.py
- idaes/generic_models/properties/core/generic/generic_property.py
- idaes/generic_models/properties/core/generic/tests/test_generic_property.py
- idaes/generic_models/properties/core/generic/tests/test_utility.py
- idaes/generic_models/properties/core/generic/utility.py
This PR adds support for a number of properties required by IDAES and NAWI work.
- Adds support for molar volume and updates molar density to be calculated from molar volume
- Adds general mixing rules for molar volume to all equations of state and activity coefficient models
- Adds support for defining models for diffusivity and dynamic viscosity
- Adds tests for utility methods that were missing
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these …
> Expanding Generic Property Framework

- idaes/generic_models/properties/core/generic/generic_reaction.py
- idaes/generic_models/properties/core/generic/tests/test_generic_reaction.py
A collaborator from NAWI noted that the generic reaction framework insist that rate-based reactions have a rate form specified, even though this is not required for stoichiometric reactors. This PR relaxes that requirement to allow rate-based reactions to not be specified with a form, and to only raise an exception if reaction rate is required.
- Replace ConfiguragtionError in initial check for rate form with ha DEBUG message
- Add new ConfigurationError as part of constructing `reaction_rate` to catch cases where rate form was not specified.
- Update tests accordingly
1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top …
> Relaxing requirement for generic reactions to have rate form

- idaes/commands/extensions.py
- idaes/config.py
- idaes/util/download_bin.py
This cleans up the get-extensions download function, and lets you specify extra packages.  It also adds a tool to calculate the binary release hashes.  This is to prep for adding the Petsc solver extra.  It's big, and also not something a lot of people want.  So I don't want to add it to solvers.  The size of it may also make it hard to use GitHub actions to calculate the hashes like I have been doing.  It will probably complain about the amount of stuff I download.
You'd use something like:
```sh
idaes get-extensions --extra petsc
```
You can use the ```--extra``` options multiple times to install multiple extras, but at this point we have only petsc
1. I agree my contributions …
> Get-extensions add "extra" option and bump to 2.4.4 release 

- idaes/apps/caprese/tests/test_controller.py
- idaes/core/process_base.py
- idaes/core/property_base.py
- idaes/core/util/misc.py
- setup.py
This PR bumps the Pyomo tag for testing IDAES in order to start testing the latest version of Pyomo prior to the its next release.
- Had to make one minor change to fix a test in capresse.
-
> Bump Pyomo tag for pre-release testing

- idaes/generic_models/unit_models/mixer.py
- idaes/generic_models/unit_models/tests/test_mixer.py
The core Mixer model currently lacks code to perform constraint scaling on the energy balance.
- Add code to do constraint scaling on the Mixer energy balance if it exists
- Add a basic test for Mixer scaling
> Adding energy scaling to mixer unit model

- idaes/generic_models/unit_models/valve.py
For the valve unit model, the `report` fxn is broken because it's looking for a config entry of `valve_function`, where it should be looking for `valve_function_callback`.
> Fix report() in valve.py

- idaes/core/util/initialization.py
- idaes/core/util/misc.py
- idaes/core/util/tests/test_initialization.py
- idaes/core/util/tests/test_misc.py
`idaes.core.util.initialization.propagate_state` currently handles indexed arcs incorrectly. This PR corrects this issue.
- Deprecate and move the functionality of `idaes.core.util.misc.copy_port_values` to `propagate_state`. `propagate_state` should be able to replace all instances of `copy_port_values` without issue.
- More forgiving duck-typing in `propagate_state` to handle indexed Arcs/Ports
- Tests now check indexed arcs and ports …
> Fixing issue with IndexedArcs in propagate_state

- idaes/generic_models/properties/core/generic/generic_property.py
Revises a conditional statement that should've checked for molar flow basis rather than mass flow basis in `generic_property.py`
- change `MaterialFlowbasis.mass` to `MaterialFlowbasis.molar` 
> Minor fix in Generic Property Model

- setup.py
This picks up the Pyomo 6.1.2 tag (and the rename of `Set.card()` to `Set.at()`)
- Bump Pyomo tag for development
> Bumping Pyomo tag to 6.1.2

- idaes/apps/caprese/dynamic_block.py
- idaes/apps/caprese/util.py
`OrderedSet.__getitem__` is deprecated in the latest release of Pyomo. This PR updates Caprese modules to not rely on it.
> Remove `OrderedSet.__getitem__` from Caprese modules

- docs/user_guide/commands/env_info.rst
- docs/user_guide/commands/get_extensions.rst
- docs/user_guide/commands/index.rst
- idaes/commands/convergence.py
- idaes/commands/env_info.py
- idaes/commands/tests/test_commands.py
- idaes/commands/wrap_solver_wsl.py
- idaes/core/util/env_info.py
- idaes/core/util/model_serializer.py
- idaes/core/util/tests/test_env_info.py
- idaes/power_generation/flowsheets/supercritical_steam_cycle/supercritical_steam_cycle.py
- idaes/power_generation/unit_models/helm/turbine_multistage.py
- idaes/tests/test_solvers.py
Not sure I took the best approach here, so don't feel bad about making suggestions.
Adds a command to print info about
-  IDAES version
- Python version
- OS version
- Pyomo version
- Dependency versions
- Extra package versions (by this I mean packages users have to install to use some things)
```sh
(idaes-pse) C:\Users\EslickJ\git\idaes-pse\idaes\core\util>idaes environment-info
IDAES
IDAES Version: 1.11.0.dev0
IDAES Git Hash: 9ca7252853c51b04b9b2c265c73b581104e923fc
Pyomo
Pyomo Version: 6.0.2.dev0
OS
Platform: Windows
Release: 10
Version: 10.0.19041
Python
Python Version: 3.9.4 (default, Apr  9 2021, 11:43:21) [MSC v.1916 64 bit (AMD64)]
Dependencies
backports.shutil_get_terminal_size: 1.0.0
bunch: 1.0.1
click: 7.1.2
colorama: 0.4.4
flask: 2.0.0
flask-cors: 3.0.10
jupyter: 1.0.0
lxml: …
```
> Add a command to print a bunch of environment info

- idaes/core/util/scaling.py
- idaes/core/util/tests/test_scaling.py
Related to Pyomo/pyomo#2093
In Pyomo 6.1+, ranged constraints will sometimes not report as equality constraints when the bounds are identical. Currently, the constraint scaling functionality transforms equality constraints into range constraints. This PR ensures equality constraints are transformed to equality constraints.
- Change constraint scaling functions to check for equality constraints
- Add tests to ensure the underlying logical expressions are held harmless by the transformation
- Change `__none_mult` to `__none_left_mult` to ensure we don't scale constraints by `None`.
1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at …
> Ensuring constraint scaling maintains constraint type

- idaes/generic_models/properties/core/generic/generic_property.py
- idaes/generic_models/unit_models/mixer.py
- idaes/generic_models/unit_models/separator.py
- idaes/generic_models/unit_models/tests/test_mixer.py
An issue with mixer and separator scaling when components are not in a phase.
> Fix mixer and spe scale when components not in a phase

- idaes/generic_models/properties/core/reactions/equilibrium_constant.py
- idaes/generic_models/properties/core/reactions/rate_constant.py
Equilibrium nd rate constants for activity based reactions were erroneously assigned units based on activity having units of [amount]/[volume] when they should be dimensionless.
- Correct assignment of units to equilibrium constants in activity case
-
> Correcting units for activity-based rate and equilibrium constants

- idaes/surrogate/pysmo/sampling.py
This is a small change to use `np.random.rand()` in place of `random.rand()` in the Latin Hypercube method.  This change makes the random source used across all the sampling methods consistent.
Being consistent with the random source allows a user to set the RNG seed in a systematic way outside the sampling methods and produce repeatable outputs for testing purposes.
- Use `np.random.rand()` for consistency
- Remove `random` import …
> Use consistent randomness sources in PySMO sampling methods

- idaes/generic_models/properties/core/eos/ceos.py
Fixes an error mixing cubic EOS in one phase with ideal in the other.
> Fix problem with mixing ideal and cubic eos

- idaes/core/unit_model.py
- idaes/core/util/tables.py
- idaes/core/util/tests/test_tables.py
- setup.py
-Fixes issue with stream tables for the distillation column described in #96
As suggested by #480, I took a look at `_get_state_from_port` to see whether we could make it public. Because it fails in instances where a naïve user might expect it to succeed (such as on the outlet ports of the Flash unit), I elected to not make it public at this time.  In the course of the investigation, however, I found that the previous implementation did not work when a port was extended through Pyomo (such as in the `TrayColumn` feed). Therefore I reimplemented it along the lines @jsiirola suggested in #480 . We can then close #480 as inadvisable at the moment.
- Reimplement `_get_state_from_port`
- Remove the `_state_block` attribute from ports generated through `add_port` functions
- Add additional …
> Reimplement _get_state_from_port

- docs/technical_specs/core/util/tags.rst
- idaes/core/util/misc.py
- idaes/core/util/tags.py
- idaes/core/util/tests/test_tag_svg.py
- idaes/core/util/tests/test_tags.py
This mainly updates updates the svg_tag function to use the new model tag classes.  It also move some feature (conditional formatting, division by zero trapping, and no value trapping) to model tags, as it was previously part of the svg output function.
I moved the svg_tag function and updated the API.  The new function support the old API and old import location.  At some future point we can add deprecation warnings.  I don't want to bother anyone with it yet though. 
2. I represent I am authorized to make the contributions and grant the license. …
> Update Tagged SVG Output to use ModelTagGroups

- docs/technical_specs/model_libraries/generic/control/pid.rst
- idaes/apps/caprese/examples/cstr_model.py
- idaes/core/components.py
- idaes/core/flowsheet_model.py
- idaes/core/property_base.py
- idaes/core/property_meta.py
- idaes/core/reaction_base.py
- idaes/core/tests/test_components.py
- idaes/core/tests/test_control_volume_0d.py
- idaes/core/tests/test_control_volume_base.py
- idaes/core/tests/test_flowsheet_model.py
- idaes/core/tests/test_property_base.py
- idaes/core/tests/test_reaction_base.py
- idaes/core/tests/test_unit_model.py
- idaes/core/util/tests/test_initialization.py
- idaes/core/util/tests/test_pid_initialization.py
- idaes/dmf/tests/for_propindex.py
- idaes/generic_models/properties/core/generic/generic_property.py
- idaes/generic_models/properties/core/generic/generic_reaction.py
- idaes/generic_models/properties/core/generic/tests/test_generic_property.py
- idaes/generic_models/properties/core/generic/tests/test_generic_reaction.py
- idaes/generic_models/properties/cubic_eos/tests/test_cubic_prop_pack.py
- idaes/generic_models/unit_models/tests/test_mixer.py
- idaes/generic_models/unit_models/tests/test_separator.py
- idaes/power_generation/unit_models/helm/tests/test_condenser_ntu.py
- idaes/power_generation/unit_models/helm/tests/test_turbine_inlet.py
- idaes/power_generation/unit_models/helm/tests/test_turbine_outlet.py
Removing some backwards compatibility code for features that have been deprecated for over a year.
- Units are now required for dynamic time domains
- Pyomo units must be used for all property packages (can use `dimensionless` to ignore units, but must be explicit).
- Property packages must use `Phase` and `Component` objects rather than creating phase and component lists
- Developers can no longer directly set `state_block_class` and `reaction_block_class`
2. I represent I am authorized to make the contributions and grant the license. If my …
> Removing deprecated features

- idaes/core/util/misc.py
- idaes/core/util/tests/test_misc.py
- idaes/generic_models/properties/core/examples/tests/test_CO2_bmimPF6_PR.py
@dallan-keylogic identified an issue where using `set_value()` on the IDAES `GeneralVarLikeExpression` component would overwrite the expression with the new value, which was undesired behaviour. This PR overloads `set_value` to raise an `Exception` in normal use, but retains a `force` option to allow users to change the expression if desired.
- Overloads `set_value()`
- Adds new tests for `set_value`
- Fixes a case where `value()` should have been used in a test.
2. I represent I am authorized to make the contributions and grant the license. If my …
> Adding set_value method to GeneralVarLikeExpression

- idaes/generic_models/properties/core/state_definitions/FPhx.py
- idaes/generic_models/properties/core/state_definitions/FTPx.py
- idaes/generic_models/properties/core/state_definitions/FcPh.py
- idaes/generic_models/properties/core/state_definitions/FcTP.py
Looking over the output of an example notebook in https://github.com/IDAES/examples-pse/pull/65 revealed a deprecation warning that should be fixed.
- Change cases where a cardinal index was used to get a value from Pyomo Sets
-
> Fixing deprecation warning about using cardinal indices on Pyomo Sets

- docs/technical_specs/model_libraries/power_generation/carbon_capture/mea_solvent_system/unit_models/phe.rst
- idaes/power_generation/carbon_capture/mea_solvent_system/properties/liquid_prop.py
- idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/column.py
- idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/plate_heat_exchanger.py
- idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/tests/test_plate_heat_exchanger.py
This is the first steps in standardising and genericising the MEA column model
- Renamed `PHE` to `PlateHeatExchanger`
- Cleaning up logger messages
- Removed unnecessary reference to `time`
- Renamed `N_v`
- Began moving definition of mass transfer species to unit model level
- Lots of linting
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required …
> Standardize Gen1 column model (Part 1)

- idaes/core/util/testing.py
Corrects the path to the replacement for `get_default_solver`
-
-
> Fixing deprecation warning for get_default_solver

- idaes/core/util/tables.py
- idaes/ui/flowsheet.py
- idaes/ui/fsvis/static/css/main.css
- idaes/ui/fsvis/static/js/stream_table.js
- idaes/ui/tests/demo_flowsheet.json
- idaes/ui/tests/serialized_boiler_flowsheet.json
Fixes #322 
Adding units to the stream table view that shows up on the UI page. The units are generated randomly using the pyomo library to read the `derived_units` units from the FlowSheetBlock.
> Adding units to stream_table

- .github/workflows/core.yml
- Change GHA workflow definition file so that pytest jobs are properly set up to generate and upload coverage reports to Codecov
It looks like Codecov is back in business again, although I'm not exactly sure why it stopped working in the first place.
- The main difference in this PR was adding the `--cov-report` pytest CLI flag, whereas previously only `--cov` was being used
- My best guess is that some defaults in the `pytest`/`pytest-cov`/`coverage`/Codecov chain changed, and whatever report was being generated with the sole `--cov` flag ceased to be compatible with the Codecov upload
- In any case, I've added the optional `fail_ci_if_errors = True` for the Codecov upload step. I'm not exactly sure what it does but hopefully it should increase the chances that we'll realize if something …
> Configure pytest jobs in GitHub Actions to get coverage reports

- idaes/surrogate/alamopy.py
- idaes/surrogate/tests/test_alamopy.py
@MAZamarripa identified a couple of bugs in the Alamopy wrapper.
- Corrects domain validators for mono- and multi-power config arguments to allow for any real number instead of just integers.
- Fixes bug with `evaluate_surrogate` method where calling the method a second time would result in an exception due to `fcn` being accessed before assignment.
- Added tests for the above cases.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I …
> Fixing some bugs in alamopy wrapper

- README.md
- idaes/core/util/tables.py
- idaes/generic_models/properties/core/examples/tests/test_ASU_PR.py
- idaes/generic_models/properties/core/examples/tests/test_ASU_PR_Dowling_2015.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcTP.py
- idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_Ideal_VLE.py
- idaes/generic_models/properties/core/examples/tests/test_CO2_bmimPF6_PR.py
- idaes/generic_models/properties/core/examples/tests/test_HC_PR.py
- idaes/generic_models/properties/core/examples/tests/test_HC_PR_vap.py
- idaes/power_generation/unit_models/boiler_heat_exchanger_2D.py
- idaes/ui/tests/test_flowsheet.py
- setup.py
This updates the Pyomo tag to the 6.2 release. I also updated the supported versions of Python in `setup.py` and the `README` because I noticed they were out of date. Looks like we are running tests for Python 3.9.
> Updating Pyomo version to the 6.2 release

- idaes/generic_models/unit_models/separator.py
Jinliang found a bug in the separator initialization code when assembling indexing tuples from time, outlet and an arbitrary set of keys from a given state variable.
- Fixes indexing bugs
-
> Fixing indexing issue in separator initialization

- docs/technical_specs/core/control_volume_1d.rst
- idaes/core/control_volume1d.py
- idaes/core/tests/test_control_volume_1d.py
- idaes/gas_solid_contactors/unit_models/bubbling_fluidized_bed.py
- idaes/gas_solid_contactors/unit_models/moving_bed.py
- idaes/gas_solid_contactors/unit_models/tests/test_BFB.py
- idaes/gas_solid_contactors/unit_models/tests/test_MB.py
We have a number of unit models with multiple 1D control volumes where the length of each domain is equal. Previously, we needed to create a set of constraints to equate the length in each domain, and often added a separate unit level variable for length. This PR adds an optional argument to `CV1D.add_geometry` which allows the user to specify an existing component (Var, Param or Expression) to use for the length of the domain. If this argument is provided, `cv.length` becomes a reference to the provided component instead of a new variable.
- Add new optional `length_var` argument to `CV1D.add_geometry` with tests.
- Add (short) reference to this feature in the docs
- Update gas-solids contactor models to make use of the new feature.
By contributing to this software project, I agree to …
> Adding option to use external length variable in 1D control volumes

- idaes/generic_models/properties/core/generic/tests/test_vle.py
- idaes/generic_models/unit_models/tests/test_skeleton_unit_model.py
- idaes/power_generation/costing/tests/test_NGCC_costing.py
There were a few cases where the outcome of some `component` tests relied on effects of `unit` tests. This resulted in failures of these tests if the `component` tests were run in isolation. This slipped through testing as we almost never run `component` tests in isolation (at least not as part of the CI). …
> Fixing some inter-dependency between component and unit tests

- docs/technical_specs/core/util/model_serializer.rst
- idaes/generic_models/properties/core/generic/generic_property.py
- idaes/generic_models/unit_models/column_models/tests/test_solvent_condenser.py
The most recent version of Pyomo has begun emitting warnings when the value of a `Var` is set outside its bounds. Some IDAES code was triggering these warnings, so this PR addresses the cause of those.
- When initializing mole fractions in the generic property package, ensure that the value is never set less than the lower bound.
- Correct bounds in one example code snippet where the value was being set outside the bounds.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual …
> Fixing some Pyomo warnings

- idaes/core/util/exceptions.py
- idaes/core/util/tests/test_exceptions.py
- idaes/generic_models/properties/activity_coeff_models/activity_coeff_prop_pack.py
- idaes/generic_models/properties/core/examples/tests/test_ASU_PR.py
- idaes/generic_models/properties/core/examples/tests/test_ASU_PR_Dowling_2015.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
- idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcTP.py
- idaes/generic_models/properties/core/examples/tests/test_BT_PR.py
- idaes/generic_models/properties/core/generic/generic_property.py
- idaes/generic_models/properties/core/generic/utility.py
- idaes/generic_models/properties/cubic_eos/cubic_prop_pack.py
- idaes/generic_models/properties/cubic_eos/tests/test_BT_example.py
- idaes/generic_models/properties/tests/test_harness.py
- idaes/generic_models/properties/tests/test_iapws95_with_harness.py
- idaes/generic_models/properties/tests/test_swco2_with_harness.py
Currently, initialization routines have no way of telling the user that they failed beyond logger messages. This PR adds a new InitializationError that all initialization routines should raise if there is a failure during initiation (e.g. the final solve is not feasible).
- Adds new InitializaitonError
- Implements code to raise InitializationErrors in most core property packages.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I …
> Adding Exception for models to raise if initialization fails

- docs/technical_specs/model_libraries/generic/unit_models/stoichiometric_reactor.rst
The docs for the stoichiometric reactor were missing variable names for the extent of reaction terms which are common performance specs.
- Added mention of names for extent of reaction terms.
- Also added mention of adding conversion/selectivity terms.
> Improving docs for stoichiometric reactor

- idaes/commands/tests/test_commands.py
- Move `pytest.mark.skip` from entire test module to individual failing test
> Temporarily skip failing integration test to address #493

- idaes/surrogate/keras_surrogate.py
- idaes/surrogate/tests/test_keras_surrogate.py
- setup.py
- using pyomo attempt_import to make 'tensorflow.keras' an optional import and skipping all of test_keras_surrogate file to skip tests if tensorflow.keras is not available
- removing tensorflow from the list of required dependencies
-
-
> Making tensorflow optional in test_keras_surrogate

- .github/workflows/core.yml
- .github/workflows/integration.yml
- idaes/dmf/tests/test_getver.py
- setup.py
- Test failures due to missing `idaes/surrogate/tests/alamotrace.trc` files
- Add pattern for `*.trc` files to `setup.py` so that they are included when installing IDAES in site-packages (non-editable) mode
- Add CI check to test site-packages installation to catch future occurrences …
> Include *.trc files in site-packages (non-editable) installation

- idaes/generic_models/properties/core/generic/generic_property.py
- idaes/surrogate/pysmo/tests/test_utils.py
There was a bug introduced in a recent PR that caused KeyErrors during initialization of generic property models due to sparse phase-component sets.
- Add checks for sparse phase-component sets in the new code.
- Add a check for potential division-by-zero errors in cases with spare phase-component sets. …
> Fixing bug in generic properties initialization

- .github/workflows/core.yml
- .github/workflows/integration.yml
- .pylint/idaes_reporters.py
- README.md
- docs/getting_started/index.rst
- idaes/surrogate/alamopy.py
- setup.py
- Remove Python 3.6 from docs and CI and update Python versions accordingly
- Remove 3.6-specific workarounds from the codebase
> Drop support for Python 3.6

- idaes/core/util/tags.py
- idaes/core/util/tests/test_tags.py
In the ModeTag class, when you tag a slice convert it to a Reference instead of storing the slice.  That makes the tag value easier to deal with since the indexing is preserved better.
> Change Slice Tags to Reference

- idaes/power_generation/carbon_capture/mea_solvent_system/properties/MEA_solvent.py
Adding units for the Keq expression in the MEA solvent property package
- Multiply Keq expression by m3/mol
> Adding units for Keq in MEA solvent properties

- idaes/ui/fsvis/tests/test_fsvis.py
#654 
Disabling browser windows being opened by the `test_visualize_save_loadfromsaved` test at tes_fsvis.py
-
-
> Fix #654 where tests in test_fsvis.py don't open browser windows anymore

- idaes/commands/base.py
- idaes/commands/tests/test_commands.py
- setup.py
- Click 8 is a dependency of Black, which has recently released its first stable release
- As many of IDAES's dependencies depend on Black, this effectively results in IDAES having to support Click 8 as well
- The Click requirement for IDAES was fixed to `<8` because of an unspecified error occurring (at the time) with Click 8 …
> Make IDAES compatible with Click 8

- idaes/generic_models/properties/core/eos/tests/test_ideal.py
- idaes/generic_models/properties/core/reactions/tests/test_equilibrium_constant.py
Replicates part of #695 that was fixing some issues with checking some string comparisons for expression forms. I tried using `pyomo.core.expr.compare.compare_expressions()` with no success, and decided we needed this merged sooner rather than later so went with the old fix.
-
-
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf …
> Fixing string checking of Expressions

- idaes/core/solvers/petsc.py
- idaes/core/solvers/tests/test_petsc.py
Previously, if a variable with multiple references had a scaling factor, it would get descaled once for each reference. This PR ensures they are descaled only once.
> Prevent references from being descaled multiple times

- idaes/ui/fsvis/static/css/main.css
- idaes/ui/fsvis/static/js/toolbar.js
- idaes/ui/fsvis/templates/index.html
Adds Toggle to Streams' names in the flowsheet canvas
-
-
> Adding a toggle to hide the stream names and show them

- setup.py
- The changes introduced in #683 turned out to be not backwards-compatible with Click 7 and below, so we should specify Click 8 as the minimum version
- Add version constraint for Click version 8 or greater
> Require Click version 8 or greater

- idaes/power_generation/flowsheets/rsofc/rsofc_soec_flowsheet.py
Updated soec flowsheet to use equivalent sofc stack values of number of cells (3.222e6) and area per cell (550 cm2). All results including costing and optimization were also updated
-
-
> rsofc_soec mode update

- .github/workflows/core.yml
- .github/workflows/integration.yml
- docs/tutorials/getting_started/index.rst
- idaes/generic_models/properties/core/coolprop/tests/test_coolprop_wrapper.py
- idaes/generic_models/properties/core/eos/tests/test_enrtl.py
- idaes/surrogate/keras_surrogate.py
- idaes/surrogate/tests/test_keras_surrogate.py
- idaes/tests/test_headers.py
- setup.py
- Test failures caused by `addheader/omlt not available` errors
- Being able to run (a reasonable subset of) the IDAES test suite regardless of how it was installed is very valuable to validate installation
- We want this process to be as reliable and simple as possible
- Therefore, for simplicity, we should implement a policy that the test suite should run without errors having only `pytest` as a strict requirement
- In other words, any test that requires extra dependencies should be seamlessly skipped when that dependency is not available
- Add `pytest.importorskip()` to skip `test_headers` module if `addheader` package is not available
- Move `omlt` to `optional` dependencies similarly to `tensorflow` in `setup.py` to match Conda package
- Add optional import logic to `keras_surrogate` …
> Ensure that pytest is the only strict requirement for running test suite for all installation modes

- idaes/core/util/tags.py
Just fix a warning that has a redundant deprecated "DEPRECATED: DEPRECATED:".   
> Fix redundant deprecation in warning

- idaes/core/util/tests/test_tags.py
A recent new release of `pint` broke some string comparisons in our tests.
- Fix string comparison to build expected expression and cast to string rather than hard code expected string.
-
> Fixing test failure due to new pint release

- idaes/models_extra/column_models/properties/MEA_solvent.py
- idaes/models_extra/column_models/properties/tests/test_mea_solvent.py
A small correction is made to the MEA solvent viscosity model in the MEA_solvent property package.
Correcting the MEA solvent viscosity model, to ensure accurate property calculations.
- The definition of intermediate term r in the expression of MEA solvent viscosity model (apparent liquid phase mass fraction of MEA on a CO2 free basis)
- Liquid phase viscosity and diffusivity values are updated in the tests …
> MEA solvent viscosity calculation correction

- idaes/apps/grid_integration/tests/test_coordinator.py
Given Prescient is an optional dependency, we need to skip the tests which require Prescient.
- Add pytest.importorskip() for test that requires prescient.
-
> add pytest importorskip for test that requires prescient

- idaes/core/util/model_serializer.py
- idaes/core/util/tests/test_model_serializer.py
Makes me wonder if I should rewrite the serializer.  BooleanVar is not a Var, so when serializing it was falling back on generic Component and causing an error.
-
-
> Fix BooleanVar in model serializer

- idaes/apps/grid_integration/coordinator.py
- idaes/apps/grid_integration/examples/thermal_generator.py
- idaes/apps/grid_integration/tests/test_bidder.py
- idaes/apps/grid_integration/tests/test_coordinator.py
- idaes/apps/grid_integration/tests/test_integration.py
- idaes/tests/prescient/test_prescient.py
The `grid_integration` code requires `prescient` to work and imports it as part of the code. The existing code and tests were not correctly handling cases where `prescient` was not available resulting in test failures for systems without it.
- Fixed misuse of `pytest.importortest`
- Fixing some other issues with conditional importing of `prescient`.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received …
> Fixing skipping tests for prescient

- idaes/core/util/model_serializer.py
- idaes/core/util/tests/test_model_serializer.py
_BlockData is not in the components to serialize (since it is component data), so if you wanted to serialize a block data object as the root object, it wouldn't work since _BlockData isn't in the list of component classes to serialize.  I fixed this by catching _BlockData and pretending it's a Block when looking at the list of components to serialize.  This should only happen when a _BlockData object is the root object.  Otherwise, it only shows up as component data.  Sorry I know that's confusing, but it fixes #826
2. I represent I am authorized …
> Fix serializing with top level BlockData

- .github/workflows/core.yml
- .github/workflows/integration.yml
- At some point in the last few months (thanks to @andrewlee94 for the most recent suggestion to implement this) GitHub Actions added the functionality to tag workflows so that only one run is allowed at any given time
- If the `cancel-in-progress` option is set to `true`, already running workflows will be canceled
- This is very useful for us since it reduces the need of "manual corralling" workflow runs when merging several PRs one after the other
- By choosing the concurrency `group` opportunely, we can require that at most one workflow run per PR should be running at a given time, so whenever a new commit is pushed to the PR head branch (e.g. by merging the current `main` into it), outdated and therefore unneeded workflow runs are cancelled automatically
-
-
By contributing to this …
> Configure GHA run serialization to automatically cancel redundant workflow runs

- setup.py
This updates the IDAES pyomo reference to the final 6.4.1 release
- Update pyomo prerelease tag to 6.4.1.zip
- Update minimum Pyomo version
> Update pyomo to the 6.4.1 release

- idaes/models/unit_models/pressure_changer.py
- idaes/models/unit_models/tests/test_pressure_changer.py
In WaterTAP, we noticed that having a property model with `EnergyBalanceType.none` would be incompatible with a Pump unit. Thus, to be compatible with the Pump, the property model currently needs to have  `EnergyBalanceType.enthalpyTotal` set. However, enthalpy is not necessary for the Pump; we only really care about volumetric flow rate, pressure (head) and efficiency to then calculate work. 
In short, the `work` variable is only ever created on a ControlVolume Block when `EnergyBalanceType.enthalpyTotal` is set which shouldn't always be the case. For more details, please have a look at this discussion in our WaterTAP repo: https://github.com/watertap-org/watertap/issues/651
- add conditional check before Reference connecting `control_volume.work` to `self.work_mechanical` in …
> Create work term for Pressure Changer with EnergyBalanceType.none

- idaes/models_extra/power_generation/unit_models/helm/tests/test_turbine_multistage.py
- idaes/models_extra/power_generation/unit_models/helm/turbine_multistage.py
This fixes up the multistage steam turbine test.  It's required for new IAPWS binaries to pass, but it's also an improvement in general.  The main change is including the reheater temperature constraint before initializing the reheater.  This keeps the turbine from seeing a weird temperature.  It also cleans up a little out dated code.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to …
> Fix multistage turbine test

- idaes/core/base/costing_base.py
- idaes/core/base/tests/test_costing_base.py
Defining additional unused flows in a costing package can cause additional variables and constraints to be passed to Ipopt for flowsheets not utilizing those flows. This can sometime cause "spooky action at a distance" on sensitive flowsheets. See watertap-org/watertap#684 for more detail.
- ~~Fix unneeded `aggregate_flow_costs[ftype]` variables on the flowsheet costing block to `0` instead of constraining them to be `0`, eliminating (a) unneeded variable(s)/constraint(s) from the model.~~
- Define a new set, `used_flows` of flows which have been registered with the costing package. This allows for the elimination of unneeded variable(s) and constraint(s) as well as two `try/except` blocks in the costing package.
By contributing to this software project, I agree to the following terms and …
> Only aggregating flows with at least one registered flow

- idaes/core/solvers/petsc.py
I ran across an issue with the petsc interface where the petsc interface tests fail if petsc is installed in the system (and not just locally in the IDAES configuration directory).  This PR resolves that (it will look for `petscpy` both along side the `petsc` found in the system PATH as well as the IDAES configuration directory).  In addition, it defers the import of the petsc binary interfaces until they are actually needed.
- look in additional locations for the `petscpy` interface
- Do not permanently change the `sys.path`
- Defer the import of the petsc binary interfaces until their first use
1. I agree my contributions are submitted under the license terms described in the …
> Update how petsc binary io interface is imported

- idaes/core/base/process_block.py
The PR removed the backwards compatibility code to support the deprecated `default` argument when constructing `ProcessBlocks`
-
-
> Removing backwards compatibility for default argument

- .github/workflows/core.yml
- .github/workflows/integration.yml
- `ubuntu-18.04` is deprecated
- Switch from `ubuntu-18.04` to `ubuntu-20.04`
- Decouple readable labels (`linux`, `win64`) from runner image keys (`ubuntu-20.04`, `windows-2022`) to avoid having to update CI job names (e.g. in the branch protection rules) after future updates
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of …
> Switch Linux CI jobs to ubuntu-20.04 runner image

- idaes/apps/grid_integration/bidder.py
- idaes/apps/grid_integration/coordinator.py
- idaes/apps/grid_integration/tests/test_bidder.py
for thermal generators that are `agc_capable` there could be an attribute called `p_min_agc` and `p_max_agc`. Prescient/Egret will expect these to be such that:
`p_min <= p_min_agc <= p_max_agc <= p_max`
While assembling the bids, update the min and max agc power to be equal to the min and max power.
Nuclear double loop example runs into this problem
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received …
> Grid integration: update bounds of AGC bid

- idaes/models/properties/general_helmholtz/helmholtz_state.py
- idaes/models/properties/general_helmholtz/tests/test_with_heater.py
NGCC example need the mole_frac_comp property in the pure component Helmholtz EoS, so this adds it. 
> Fix missing property mole_frac_comp for NGCC example

- idaes/models/properties/general_helmholtz/helmholtz_functions.py
- idaes/models/properties/general_helmholtz/helmholtz_state.py
I was missing this property I need in some viscosity or thermal conductivity calculations.  I do have tests for those expressions, but somehow this got through. 
> Add dens_star_mol to Helmholtz Property Block

- idaes/models/properties/general_helmholtz/components/__init__.py
- idaes/models/properties/general_helmholtz/components/co2.py
- idaes/models/properties/general_helmholtz/components/registry.py
- idaes/models/properties/general_helmholtz/helmholtz_functions.py
- idaes/models/properties/general_helmholtz/helmholtz_state.py
This lets you register new components.  Right now if you get new data files, you need to add them to the directory with the rest of the Helmholtz data files that get installed with the binaries, but when I get a chance, I want to let you specify alternate directories and maybe alternate names when you register components.  Also would be good to look into using the DMF, but I need a quick fix for now.
This also lets you have thermo properties for a component without implementing transport properties.
I have tested this with other components that we are not currently making available and don't have transport properties and it works.  I know I need to rework the Helmholtz docs, so I'll do that in another new PR ASAP. 
-
-
By contributing to this software project, I agree to the following …
> Add a way to register new helmholtz components

- idaes/models/unit_models/heat_exchanger_1D.py
Gets rid of time index for equation in `HeatExchanger1D` equating hot and cold side flow lengths.
> Get rid of spurious time index

- docs/reference_guides/model_libraries/generic/unit_models/heat_exchanger.rst
- idaes/models/unit_models/heat_exchanger.py
- idaes/models/unit_models/tests/test_heat_exchanger.py
Add the smooth LMTD approximation from
Kazi, S., M. Short, A.J. Isafiade,
L.T. Biegler. "Heat exchanger network synthesus with detailed exchanger
designs - 2. Hybrid optimization strategy for synthesis of heat exchanger
networks". AIChE Journal, 2020.
This handles the case where the temperature difference at both ends of the heat exchanger is the same, and it doesn't deviate much from the standard LMTD calculation.  It's potentially more robust even when you don't expect there to be an issue with LMTD since you may evaluate LMTD near the singularity while solving.
This only adds a delta T callback, test and docs.  It doesn't change anything else, so at the very least it won't break anything. 
By contributing to this software project, I agree to the following terms and conditions for my …
> Add smooth LMTD approximation

- idaes/core/surrogate/surrogate_block.py
There was a stray print statement in `SurrogateBlock`.
- Replace print statement with `log.debug`
-
> Fixing print statement in SurrogateBlock

- idaes/core/base/costing_base.py
- idaes/core/base/tests/test_costing_base.py
- Adding `USD_2021` units to the IDAES currency dictionary, as these units will be required for applications in other subtasks.
> Add 2021 CEPCI Value

- idaes/__init__.py
- idaes/ver.py
- Until 2.0.0 (i.e. final) is released, running `pip install idaes-pse` will result in the latest stable release on the 1.x series (currently 1.13.0) to be installed
- This PR adds a deprecation message that is emitted whenever the root `idaes` module is imported (i.e. once per process)
- If users wish to continue using the unsupported v1 series without the message, they are provided instructions to install 1.13.0 (which is functionally identical, but without the warning)
- Add deprecation warning to be displayed whenever `idaes` is imported (once per process)
1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of …
> Add global deprecation warning to 1.13 series to notify users before 2.0.0 is released

- docs/how_to_guides/custom_models/unit_model_development.rst
Fixing a one-word typo I found in the documentation.
-
-
> Fix typo in model development documentation

- idaes/core/surrogate/alamopy.py
- idaes/core/surrogate/tests/test_alamopy.py
ALAMO uses `"ln"` to represent natural logarithms, however the interface was expecting `"log"`.
- Update expression parser to correctly substitute `log` function for `"ln"`.
-
> Fixing definition of log in ALAMOpy

- idaes/config.py
- idaes/core/solvers/ipopt_l1.py
- idaes/core/solvers/tests/test_solver_config.py
- idaes/core/solvers/tests/test_solvers.py
This adds a solver factory for ipopt_l1 and fills in some config blocks to make it easier to configure with the IDAES config system.  **To use this,** you need to ``from idaes.core.solvers import ipopt_l1`` 
> Add Ipopt L1 solver factory

- docs/reference_guides/model_libraries/gas_solid_contactors/unit_models/moving_bed.rst
- idaes/models_extra/gas_solid_contactors/unit_models/moving_bed.py
- idaes/models_extra/gas_solid_contactors/unit_models/tests/test_MB.py
For counter-current flow systems, spatial discretizations of the two phases should have "opposite direction", e.g. forward for the solid phase and backward for the gas. To approximate finite volume methods, these should be "upwind" with respect to direction of flow. This PR adds options to the moving bed unit model to allow users to specify discretizations of the two phases independently.
- Add `gas_transformation_scheme` and `solid_transformation_scheme` config options to the moving bed unit model. These are only supported if `dae.finite_difference` is used for `transformation_method`
1. I agree my contributions are submitted under the license terms described in the LICENSE.txt …
> Moving bed with bidirectional spatial discretization

- idaes/core/base/control_volume0d.py
- idaes/core/base/control_volume1d.py
- idaes/core/base/control_volume_base.py
- idaes/core/base/tests/test_control_volume_0d.py
- idaes/core/base/tests/test_control_volume_1d.py
- idaes/core/util/model_statistics.py
- idaes/models/properties/modular_properties/eos/ceos.py
Pyomo is working on some changes to how expressions are generated, and in the process is changing some behaviours that IDAES has unconsciously relied upon. The most significant change is that `0*` terms will remain within the expression during unit consistency checks whereas before they were ignored. Control volumes (written before units) used this behaviour to drop unnecessary terms, but this will now cause issues when asserting unit consistency.
- Rewrite methods in control volumes which generate balance expressions to only include terms if required (rather than adding a 0 term).
- Comment out two placeholder terms in modular CEOS code for potential future functionality.
- Updated `large_residual_set` method to catch `TypeErrors` that now occur when constraints have a body containing a …
> Rework control volume code to remove unneeded terms.

- idaes/core/surrogate/pysmo/kriging.py
- idaes/core/surrogate/pysmo/polynomial_regression.py
- idaes/core/surrogate/pysmo/radial_basis_function.py
- idaes/core/surrogate/tests/test_pysmo_surrogate.py
#1065 
Fixes potential NumPy errors in surrogate model expression generation when inputs are of mixed pyomo types, e.g scalar and indexed variables. 
- specify ``dtype=object`` in PySMO when creating Numpy arrays from a list of pyomo variables.
- Add test for mixed variable input types. …
> Fix NumPy array creation error by specifying object type

- idaes/models/properties/modular_properties/eos/enrtl.py
- idaes/models/properties/modular_properties/eos/enrtl_reference_states.py
- idaes/models/properties/modular_properties/eos/tests/test_enrtl.py
- idaes/models/properties/modular_properties/eos/tests/test_ideal.py
- idaes/models/properties/modular_properties/reactions/tests/test_equilibrium_constant.py
- idaes/models/properties/modular_properties/state_definitions/FPhx.py
- idaes/models/properties/modular_properties/state_definitions/FTPx.py
- idaes/models/properties/modular_properties/state_definitions/FcPh.py
- idaes/models/properties/modular_properties/state_definitions/FcTP.py
- idaes/models/properties/modular_properties/state_definitions/FpcTP.py
The upcoming PR #2722 in Pyomo changes how some expressions get rendered, which requires changes to some IDAES tests. This PR aims to make these tests more robust for the future.
- Replace some constant `ints` in the code base with `floats` to match previous output (these should have been floats anyway).
- Rework some tests of expressions to build expected expression for comparison rather than testing hard-coded strings.
- Rework some other tests to get test expression to better align with expected expression.
- Remove checking of one very complex expression (eNRTL) - this model has sufficient verification testing to ensure form is correct.
1. I agree my contributions are submitted …
> Improving some expression tests

- idaes/apps/uncertainty_propagation/tests/test_uncertainties.py
PR #1086 identified an issue where tests for the uncertainty propagation tool failed if `kaug` was not installed. The cause was identified as an error in how the test was checking for the presence of `kaug`.
- Add `exception_flag=False` to all checks for solver presence in `test_uncertainties.py`
- Clean up some imports at the same time
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to …
> Fixing check for kaug in uncertainty tests

- idaes/apps/caprese/categorize.py
As discussed in issue #945, the `categorize_dae_variables` method has been superseded by another method and should be deprecated.
- Deprecate `categorize_dae_variables` - this method was untested so no change in tests.
-
> Deprecating categorize_dae_variables

- data/config.yaml
- idaes/apps/caprese/examples/cstr_model.py
- idaes/apps/caprese/examples/cstr_nmpc.py
- idaes/apps/caprese/examples/cstr_reduced.py
- idaes/apps/caprese/tests/test_controller.py
- idaes/apps/caprese/tests/test_dynamic_block.py
- idaes/apps/caprese/tests/test_util.py
- idaes/apps/caprese/util.py
- idaes/config.py
- idaes/models_extra/gas_distribution/unit_models/tests/test_compressor.py
- idaes/models_extra/gas_distribution/unit_models/tests/test_pipeline.py
- idaes/models_extra/gas_distribution/unit_models/tests/test_pipeline_compressor.py
- idaes/models_extra/power_generation/properties/sofc/sofc_keras_surrogate.py
- idaes/models_extra/power_generation/unit_models/cpu.py
- idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_contact_resistor.py
- idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_herring_replication.py
- idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_herring_replication_interconnect.py
- idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_herring_replication_thin.py
- idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_solid_oxide_cell.py
- idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_triple_phase_boundary.py
- idaes/models_extra/power_generation/unit_models/soec_design.py
- idaes/models_extra/power_generation/unit_models/tests/test_soec_design.py
This sets the ipopt default config to have a max_iter of 200.  This can be overridden by explicitly setting max_iter if you are using get_solver() or have the IDAES solver config system turned on. I do not think this breaks any tests in the main repo, but it could break an example.  If you set the iteration limit too low pretty much all tests fail, so I know this is working, but I don't really know if 200 is too high.  At some point we should take a harder look at fragile tests and possibly tune this in the process.
The purpose of this is to let people now if they set something up that requires a suspiciously large number of iterations and to limit the amount of time a failing test can take.
By contributing to this software project, I agree to the following terms and conditions for my …
> Set default ipopt iteration limit to 200

- README.md
IDAES now has a performance test pipeline on a Sandia Jenkins server. This PR adds a badge to the README that tracks the status of the services on Jenkins (to ensure that we see when IDAES-related services go down).
- Add services badge to README
> Add Services Status Badge for Performance Suite

- .github/workflows/core.yml
I forgot to activate the C(onvention) and I(nformation) flags in our GHA run.
-
-
> Activing pylint C and I flags in GHA

- .github/workflows/core.yml
- .pylint/render_report.py
- idaes/__init__.py
- The cause of the failure seems to be an unexpected item in the dictionary containing the per-error information (which is provided by Pylint and therefore out of our control)
- The solution is to "pick and choose" what data to take from this dictionary instead of unpacking the entire rest of the `dict`
- Change how Pylint-provided data is passed to our own custom reporting classes used to render the errors …
> Resolve Pylint rendering failures

- idaes/core/util/testing.py
The `initialization_tester` function implicitly created some indexing `Set` which were not cleaned up after execution and prevented the function from being run twice on the same model.
- Explicitly create indexing `Set` in `initialization_tester` and remove when finished.
-
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of …
> Creating issue in initialaiztion tester that left Sets attached ot model

- idaes/core/util/model_statistics.py
- idaes/core/util/tests/test_model_statistics.py
The current model statistics functions do not work when provided with an `IndexedBlock` as these do not have a `component_data_objects` method. This PR updates these methods to catch cases where the block is indexed and to first iterate over the `BlockData` objects.
- Add new private generator method that checks for indexed blocks and iterates over BlockData objects if required.
- Update tests to cover indexed blocks.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property …
> Fixing model statistics to work for indexed blocks

- idaes/core/util/tests/test_model_diagnostics.py
#1143 seems to have introduced a test failure on Python 3.11 where the check for an expected error message fails (possible due to line breaks).
- Shorten expected string being tested for.
-
> Simplify error check for ipopt_with_diagnostics test

- idaes/core/base/process_block.py
- idaes/core/initialization/initializer_base.py
- idaes/core/plugins/variable_replace.py
- setup.py
With Pyomo v6.5.0, some of the methods we use to document the Config Blocks in our models have been deprecated. This PR updates the relevant lines of code to use newer methods.
- Update`process_block.py` to better format Config block and suppress deprecation warnings.
- Update how Config blocks are included in Initializers. …
> Update approach for documenting Config Blocks

- setup.py
- Update Prescient to today's (2023 Apr 3) release
- Remove pandas < 2 requirement
> Update Prescient requirement to 2.2.2

- idaes/core/base/property_meta.py
- idaes/core/base/tests/test_property_meta.py
Add voltage units to `property_meta` file
Add voltage units to `property_meta` file to directly call `"voltage"` when using `get_derived_units` or similar utility
- Add voltage units to `property_meta` file
> Adding voltage units to `property_meta` file

- setup.py
Installation failures due to the most recent version of IPython not supporting Python 3.8
- Add constraint to `ipython` requirement for Python 3.8
> Set constraint on IPython version for Python 3.8 support

- idaes/models_extra/gas_distribution/unit_models/tests/test_compressor.py
- idaes/models_extra/gas_distribution/unit_models/tests/test_pipeline.py
Failures with https://github.com/Pyomo/pyomo/pull/2834
I was passing `ComponentMap`s as the `to_fix` argument in `ParamSweeper`, despite it being clearly documented that this should be a list.
> Correct argument type for ParamSweeper construction in pipeline tests

- idaes/core/surrogate/tests/test_pysmo_surrogate.py
- idaes/models/properties/general_helmholtz/tests/test_parameter_util.py
- idaes/models/properties/modular_properties/eos/tests/test_ideal.py
- setup.py
This is waiting on https://github.com/Pyomo/pyomo/pull/2816
This PR addresses compatibility issues in a few tests due to changes in Pyomo 6.6. These changes only affect tests and not actual functionality.
- Update expected expressions that changed in Pyomo 6.6
- Fix an issue with 0/0 caused by the new expression system
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions …
> Address Pyomo 6.6 compatibility issues

- idaes/models/properties/general_helmholtz/components/parameters/__init__.py
It seems that it is posible for have text files open with unexpected encodings, which can cause trouble reading JSON.  This sets the encoding of the Helmholtz parameter files to UTF-8 when reading literature reference information, so that it can be parsed without issue regardless of the default encoding.  …
> Add encoding to read helmholtz references

- docs/explanations/components/property_package/general/bubble_dew.rst
- docs/reference_guides/core/util/index.rst
- docs/reference_guides/core/util/math.rst
- idaes/models/properties/modular_properties/phase_equil/bubble_dew.py
- idaes/models/properties/modular_properties/phase_equil/tests/test_bubble_dew.py
From issue #1212, using the `IdealBubbleDew` approach in a system with more than just vapor and liquid phases results in unexpected (and incorrect) behavior. For these cases, `LogBubbleDew` should be used instead.
Also, this PR adds the missing docs for `idaes.core.util.math`.
- Raises a `ConfigurationError` if a user tries to use `IdealBubbleDew` with more than 2 phases (we check that there is a vapor and liquid phase elsewhere).
- Add comment to docs informing users of this limitation and instructing them to use `LogBubbleDew` instead.
- Add missing docs page for mathematical utility functions using automodule.
1. I agree my contributions are submitted under the license terms …
> Raise exception in modular properties if IdealBubbleDew used with more than 2 phases

- idaes/core/base/property_base.py
- idaes/core/base/reaction_base.py
This should fix decorators for Expressions and Constraints not working in state blocks.
> Fix for decorators in StateBlocks

- idaes/apps/uncertainty_propagation/sens.py
- idaes/core/util/model_statistics.py
- idaes/models_extra/gas_distribution/properties/natural_gas.py
- idaes/models_extra/gas_distribution/unit_models/pipeline.py
- idaes/models_extra/power_generation/unit_models/steamheater.py
- idaes/models_extra/power_generation/unit_models/waterwall_section.py
- setup.py
search and replace pyomo.core.expr.current -> pyomo.core.expr
".current" has been deprecated (see pyomo PR #2910) 
- replace deprecated imports 
-
> global search and replace pyomo.core.expr.current -> pyomo.core.expr (ref pyomo PR #2910)

- idaes/core/base/control_volume0d.py
- idaes/core/base/control_volume1d.py
- idaes/core/base/tests/test_control_volume_0d.py
- idaes/core/base/tests/test_control_volume_1d.py
This PR adds a deprecation warning for backward compatibility for cases where a control volume is set to include phase equilibrium terms but the associated property package only has a single phase.
-
-
> Adding deprecation warning for has_phase_equilibrium but only 1 phase

- idaes/models/unit_models/mscontactor.py
This PR fixes some bugs in the MS Contactor model
- Adds check to only build energy transfer terms if energy balances are being used.
- Fixes issue with closures in rules similar to #1242
> MS Contactor improvements

- idaes/models/unit_models/mixer.py
- idaes/models/unit_models/separator.py
- idaes/models/unit_models/tests/test_separator.py
- idaes/models_extra/power_generation/unit_models/soc_submodels/solid_oxide_module_simple.py
-- Fixes function closure issues outlined in #1240 and #1241 for the Separator and SOC.
> Function Scoping Fixes

- setup.py
> Add version constraint to exclude pandas 2.1 as a workaround for Pysmo test failures

- setup.py
Pandas introduced a bug in v2.1.0 that is causing Pysmo tests to fail. It looks like this bug will be fixed in the upcoming v2.1.1 pandas release.
- Setting `"pandas!=2.1.0"` in `setup.py` to avoid using the buggy version of pandas and to allow us to switch the the corrected version once it is released. …
> Setting pandas!=2.1.0

- docs/reference_guides/model_libraries/generic/unit_models/index.rst
- docs/reference_guides/model_libraries/generic/unit_models/solid_liquid/index.rst
- docs/reference_guides/model_libraries/generic/unit_models/solid_liquid/sl_separator.rst
- docs/reference_guides/model_libraries/generic/unit_models/solid_liquid/thickener0d.rst
- idaes/models/unit_models/flash.py
- idaes/models/unit_models/mscontactor.py
- idaes/models/unit_models/solid_liquid/__init__.py
- idaes/models/unit_models/solid_liquid/sl_separator.py
- idaes/models/unit_models/solid_liquid/tests/test_sl_separator.py
- idaes/models/unit_models/solid_liquid/tests/test_thickener.py
- idaes/models/unit_models/solid_liquid/thickener.py
- idaes/models/unit_models/tests/test_mscontactor.py
This PR adds a new unit model base class for separating solids and liquids such as filters and thickeners. The unit has two inlets (solid and liquid) and three outlets (solids, retained_liquid (with solids) and recovered liquid).
Docs to come, along with a derived model for thickeners.
-
-
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license …
> Solid-Liquid Separator Base Model

- .github/actions/setup-idaes/action.yml
- idaes/core/util/testing.py
- idaes/core/util/tests/test_model_diagnostics.py
- idaes/core/util/tests/test_scip_for_testing.py
- setup.py
- Add non-public util function to enable SCIP solver (using `ampl_module_scip`)
- Add `scip_solver` pytest fixture for model diagnostics tests
- If a test uses the `scip_solver` fixture (i.e. requires SCIP to run), it will be automatically skipped without the need of adding individual `pytest.mark.skipif()` markers if SCIP is not available
- Add step in GHA installation action to install `ampl_module_scip` from https://pypi.ampl.com …
> Add SCIP solver for testing

- idaes/models/unit_models/mixer.py
- idaes/models/unit_models/separator.py
- idaes/models/unit_models/tests/test_mixer.py
- idaes/models/unit_models/tests/test_separator.py
In developing a flowsheet for PrOMMiS, it was discovered that the Separator model had a degrees of freedom issue when separating streams including inherent reactions. Investigation revealed that the Separator material balances needed to include generation terms for the inherent reactions, and that this issue also exists in the Mixer.
- Refactor Mixer and Separator material balances to eliminate unnecessary zero terms
- Add necessary terms to Mixer and Separator material balances when inherent reactions are present
- Add test cases for systems with inherent reactions for Mixer and Separator
1. I agree my contributions are submitted under the license terms described in the …
> Adding support for inherent reactions in Mixer and Separator

- idaes/core/util/tests/test_model_diagnostics.py
- idaes/core/util/tests/test_utility_minimization.py
- idaes/models/properties/modular_properties/examples/tests/test_BT_PR.py
- idaes/models/unit_models/tests/test_equilibrium_reactor.py
- idaes/models/unit_models/tests/test_hx_ntu.py
Pyomo 6.7.0 added checks for fixed variables which violate bounds which caused a number of our tests to fail (about half were deliberate violations in the diagnostics tools for testing, but the rest were real).
- Updated tests to remove bound violations
-
> Fixing errors due to bound checking in nl writer

- idaes/models_extra/column_models/plate_heat_exchanger.py
- idaes/models_extra/column_models/tests/test_plate_heat_exchanger.py
- Add workaround for test failures described in #1294
- Add `xfail` marker for tests affected by #1294
> Add workaround for MEA PHE test failures

- idaes/core/util/tests/test_model_diagnostics.py
This is a temporary workaround to avoid test failures described in #1317 to hold up CI for unrelated PRs.
- Add `pytest.xfail` marker to test(s) causing failures
> Add XFAIL marker to bypass #1317 known failures

- idaes/core/util/tests/test_model_diagnostics.py
As of yesterday, CI checks on `main` have started failing again because `test_solve_candidates_milp` (which has been marked as XFAIL by #1319) started passing again:
- Remove XFAIL marker added in #1319
> Remove workaround for tests affected by #1317

- .github/workflows/core.yml
- Codecov upload failures are frustrating, as they currently require re-running the entire test suite that generates the report (20-40+ minutes)
- The proper fix is to use a Codecov upload token, saved as a repository secret
- However, this require a major restructuring of the CI workflow because `pull_request` triggers cannot access `secrets`, requiring the creation of a new, non-`pull_request` workflow
- Synchronizing triggers  and passing data between different workflows is considerably more complicated compared to doing the same between different jobs in the same workflow
- As an intermediate fix, we can separate the Codecov upload so that it runs in a separate job within the `pull_request`-triggered workflow, so that when it fails, it can be re-run separately (which should only take …
> Extract Codecov upload steps in CI workflow to dedicated dependent job

- .pylint/pylintrc
- idaes/core/util/tables.py
- `unnecessary-lambda` is a built-in Pylint check, that _might_ help addressing some of the issues with `lambda`s described in #1240 
- However, this only looks as cases where `my_func = lambda x, y: my_other_func(x, y)`, i.e where one could just simply set `my_func = my_other_func`
- More to the point, it does nothing to detect and prevent other uses of `lambda` that cause most of the issues in #1240 (specifically, by definition, the closure scope gotchas only arise when the `lambda` has fewer arguments that the function being used)
- Enable `unnecessary-lambda` Pylint check
1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the …
> Enable unnecessary-lambda Pylint check

- .github/actions/run-examples/examples_for_idaes_ci.py
CI failures due to notebooks being added by IDAES/examples#69.
- Add XFAIL pattern for new sco2 ALAMO surrogate examples
> Resolve failures in examples CI job by adding XFAIL pattern for new sco2 ALAMO surrogate examples

- docs/explanations/components/property_package/general/eos/cubic.rst
- docs/explanations/components/property_package/general/eos/ideal.rst
- docs/explanations/components/property_package/general/phase_def.rst
- idaes/core/base/components.py
- idaes/core/base/property_meta.py
- idaes/core/base/property_set.py
- idaes/core/base/tests/test_components.py
- idaes/core/base/tests/test_property_meta.py
- idaes/models/properties/modular_properties/base/generic_property.py
- idaes/models/properties/modular_properties/base/tests/test_generic_property.py
- idaes/models/properties/modular_properties/eos/ceos.py
- idaes/models/properties/modular_properties/eos/eos_base.py
- idaes/models/properties/modular_properties/eos/ideal.py
- idaes/models/properties/modular_properties/eos/tests/test_ceos_PR.py
- idaes/models/properties/modular_properties/eos/tests/test_ideal.py
This PR adds support for calculating the critical properties of mixtures in the Modular Properties framework, which is necessary to support the new Smooth VLE formulation. This is done by adding  a new method to EoS classes which contains instructions for how to calculate the mixture critical properties appropriate to the EoS.
When dealing with systems with multiple phases/EoS, only one EoS can be used thus it is necessary to determine which EoS to use. This PR applies the following steps:
1. Iterate over all phases and take the EoS associated with the first liquid phase encountered.
2. If no liquid phases are found, use the EoS associated with the vapor phase (assumes only 1 vapor phase).
3. If no liquid or vapor phases are found, raise an exception.
- Add new unit definitions for …
> Support calcuation of critical properties of mixtures in Modular Properties

- .github/actions/setup-idaes/action.yml
- idaes/core/util/tests/test_model_diagnostics.py
Make `DegeneracyHunter` tests more robust wrt different solutions, which were previously causing issues due to differences between AMPL SCIP versions.
- Apply @andrewlee94's changes from edb038b without the rest of the testing infrastructure from #1359 
- Revert the temporary fix in #1354 by setting a default input value where the `ampl-module-scip` version is not specified exactly
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I …
> Make `DegeneracyHunter` tests more robust wrt different solutions

- setup.py
> Add upper versions constraints for numpy and pandas

- setup.py
Workaround for the new version of TensorFlow that's causing #1369 
> Add constraint to exclude TensorFlow 2.16.1 and above

- idaes/core/util/scaling.py
These should be imported from `pyomo.common.numeric_types`. Also, `pyomo_constant_types` was deprecated last week (although I don't do anything about that). This PR is necessary to prevent import errors with pyomo/main, as `pyomo_constant_types` no longer exists in `pyomo.core.expr.numvalue`.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required …
> Update imports of `native_types` and `pyomo_constant_types` in scaling module

- .github/workflows/core.yml
- .github/workflows/integration.yml
- idaes/conftest.py
- pytest.ini
- Remove `--pyargs idaes` from `pytest.ini`
- Move markers definition from `pytest.ini` to `idaes/conftest.py` so that tests can be run without warnings without requiring `pytest.ini`, which is not available in non-editable installations without ad-hoc download
> Restore ability to run pytest on individual files or directories

- idaes/core/util/model_diagnostics.py
- idaes/core/util/parameter_sweep.py
- idaes/core/util/tests/test_model_diagnostics.py
- idaes/core/util/tests/test_parameter_sweep.py
In adding some more robustness tests using the new convergence analysis tools, a bug was found as well as the need for a summary report of the convergence analysis.
- Fixes bug in ParameterSweep
- Adds a report method to IpoptConvergenceAnalysis
> Tweaks to convergence tester

- .github/workflows/typos.toml
- docs/reference_guides/model_libraries/generic/costing/process_costing_sslw.rst
- docs/reference_guides/model_libraries/generic/property_models/activity_coefficient.rst
- docs/reference_guides/model_libraries/generic/property_models/ceos.rst
- docs/reference_guides/model_libraries/power_generation/costing/power_plant_costing_netl.rst
- idaes/core/solvers/tests/test_petsc_pid.py
- idaes/core/util/model_serializer.py
- idaes/models_extra/power_generation/unit_models/boiler_fireside.py
- idaes/models_extra/power_generation/unit_models/boiler_heat_exchanger_2D.py
> Resolve CI failures from new version (1.20.4) of spellchecker

- idaes/models/unit_models/gibbs_reactor.py
- idaes/models/unit_models/tests/test_gibbs.py
The current implementation of the Gibbs reactor model includes all elements in the Lagrange multipliers expressions, even if the elemental composition for a given component is 0. This leads to spurious degrees of freedom where the variable appears to be in active constraints but is multiplied y zero (and thus filtered out in the Pyomo solver writers).
- Add logic to catch these cases and exclude them from the expression.
-
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual …
> Fixing spurious DoF in Gibbs reactor model

- idaes/core/util/parameter_sweep.py
- idaes/core/util/tests/test_parameter_sweep.py
- idaes/models/unit_models/tests/test_heat_exchanger.py
- idaes/models/unit_models/tests/test_heat_exchanger_1D.py
This PR allows users of the parameter sweep tool to specify a value for an IndexedVar as a whole, rather than individual elements. All elements will be set to the same value.
- Support for indexed variables in parameter sweep tool
- Clean up a few unused imports in other test files …
> Update parameter sweep tool to support indexed vars

- idaes/core/util/scaling.py
#1364 Incompatibility between set_scaling_from_default() and generic reaction parameter data
Currently set_scaling_from_default assumes all blocks have a `get_default_scaling()` method, but this is not guaranteed.
- Add try/except around call to `get_default_scaling()`
- Log warning …
> bug fix for issue #1364: catch AttributeError in set_scaling_from_default

- .github/workflows/typos.toml
- idaes/core/util/model_diagnostics.py
- idaes/core/util/tests/test_model_diagnostics.py
See discussion on #1405
- Add basic wrapper for `pyomo.contrib.iis.mis.compute_infeasibility_explanation` to `idaes.core.util.model_diagnositics` (6099416)
- Add test for wrapper (199e2b7)
- Integrate `compute_infeasibility_explanation` into the `DiagnosticsToolbox` (a931a77)
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of …
> Infeasibility diagnostic tool

- idaes/core/base/costing_base.py
- idaes/core/base/tests/test_costing_base.py
Append USD_YYYY list with USD_2022 value from https://toweringskills.com/financial-analysis/cost-indices/
Add more up to date values for USD
- Append USD_YYYY list with USD_2022 value from https://toweringskills.com/financial-analysis/cost-indices/
> Adding USD_2022 to units library as the most recently published value

- idaes/core/util/model_diagnostics.py
This adds an option to skip checks for parallel constraints and variables, primarily for use in testing where we have cases  of known near-parallel components. This is mostly for backward compatibility with older models which we do not currently have time to fix.
-
-
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that …
> Option to skip parallel component checks

- idaes/core/util/model_serializer.py
- idaes/models/properties/modular_properties/base/generic_property.py
- idaes/models/properties/modular_properties/base/tests/test_generic_property.py
- idaes/models/properties/modular_properties/base/tests/test_noncondense.py
- idaes/models/properties/modular_properties/base/tests/test_noncondense_PR.py
- idaes/models/properties/modular_properties/base/tests/test_nonvap.py
- idaes/models/properties/modular_properties/base/tests/test_nonvap_PR.py
- idaes/models/properties/modular_properties/base/tests/test_vle.py
- idaes/models/properties/modular_properties/examples/tests/test_ASU_PR.py
- idaes/models/properties/modular_properties/examples/tests/test_ASU_PR_Dowling_2015.py
- idaes/models/properties/modular_properties/examples/tests/test_BTIdeal.py
- idaes/models/properties/modular_properties/examples/tests/test_BTIdeal_FPhx.py
- idaes/models/properties/modular_properties/examples/tests/test_BTIdeal_FcPh.py
- idaes/models/properties/modular_properties/examples/tests/test_BTIdeal_FcTP.py
- idaes/models/properties/modular_properties/examples/tests/test_CO2_H2O_Ideal_VLE.py
- idaes/models/properties/modular_properties/examples/tests/test_CO2_bmimPF6_PR.py
- idaes/models/properties/modular_properties/examples/tests/test_HC_PR.py
- idaes/models/properties/modular_properties/state_definitions/FTPx.py
- idaes/models/properties/modular_properties/state_definitions/tests/test_FTPx.py
Two issues were recently raised identifying bugs in the modular properties code.
- Correct how `phase_equilibrium_list` is created in `generic_properties.py` so that is a list (as expected) and not a dict.
- Add catch in FTPx state initialization to handle cases with non-VLE phase equilibrium
- Add regression checks for the above issues. 
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to …
> Fix some bugs in the modular properties implementation

- setup.py
Pint recently released v0.24 which changed some behavior in how dimensionless quantities are displayed and thus causes tests to start failing. However, v0.24 is only supported on Python 3.10 and greater, and thus we cannot switch tho the new version as we still support older version of Python.
- Limit pint version to <0.24
- …
> Limiting pint version

- .github/workflows/typos.toml
- idaes/core/util/model_diagnostics.py
- idaes/models/unit_models/translator.py
- idaes/models_extra/power_generation/flowsheets/subcritical_power_plant/steam_cycle_flowsheet.py
- idaes/models_extra/power_generation/flowsheets/supercritical_power_plant/SCPC_full_plant.py
- idaes/models_extra/power_generation/unit_models/helm/compressor.py
- idaes/models_extra/power_generation/unit_models/helm/condenser_ntu.py
- idaes/models_extra/power_generation/unit_models/helm/mixer.py
- idaes/models_extra/power_generation/unit_models/helm/pump.py
- idaes/models_extra/power_generation/unit_models/helm/turbine.py
- idaes/models_extra/power_generation/unit_models/helm/turbine_inlet.py
- idaes/models_extra/power_generation/unit_models/helm/turbine_multistage.py
Our external spell checker updated last month to cover some new typos, which flagged a few files in our CI runs. This resolves those errors.
> Fix Typos From June Spell Checker Update

- docs/reference_guides/model_libraries/gas_solid_contactors/flowsheets/dyn_TGA_example.rst
- docs/reference_guides/model_libraries/gas_solid_contactors/flowsheets/ss_BFB_OC_oxidation.rst
- docs/reference_guides/model_libraries/gas_solid_contactors/flowsheets/ss_BFB_methane_combustion.rst
- docs/reference_guides/model_libraries/gas_solid_contactors/flowsheets/ss_MB_methane_combustion.rst
- docs/reference_guides/model_libraries/gas_solid_contactors/unit_models/bubbling_fluidized_bed.rst
- docs/reference_guides/model_libraries/gas_solid_contactors/unit_models/fixed_bed_0D.rst
- docs/reference_guides/model_libraries/gas_solid_contactors/unit_models/fixed_bed_1D.rst
- docs/reference_guides/model_libraries/gas_solid_contactors/unit_models/moving_bed.rst
Clarifies code reference requested by https://github.com/IDAES/idaes-pse/discussions/1446.
> Add code references to gas solid contactors docs

- .github/workflows/core.yml
- .github/workflows/integration.yml
- README.md
- docs/conf.py
- docs/explanations/faq.rst
- setup.py
- Remove Python 3.8 from supported versions in docs and `setup.py`
- Remove Python 3.8 from CI workflows
> Remove support for Python 3.8

- idaes/core/base/control_volume0d.py
- idaes/core/base/flowsheet_model.py
- idaes/core/base/tests/test_control_volume_0d.py
- idaes/core/base/tests/test_control_volume_0d_scaling.py
- idaes/core/base/tests/test_control_volume_1d.py
- idaes/core/util/testing.py
This PR adjusts the units defined for the material_holdup variable constructed in ControlVolume0D, which currently only sets units as `mol` regardless of whether a mole or mass flow basis is defined. This is a problem when working with a mass flow basis. 
Notably, you would only notice this issue if you were constructing a dynamic ControlVolume0D using a mass flow basis, as we are starting to do on WaterTAP.
- set units to mol or mass basis for material_holdup, depending on basis defined for the prop pack
- add tests
2. I represent I am authorized …
> Repair erroneous units for material_holdup in CV0D when mass basis defined

- idaes/models/properties/modular_properties/base/generic_property.py
- idaes/models/properties/modular_properties/base/tests/dummy_eos.py
- idaes/models/properties/modular_properties/state_definitions/FPhx.py
- idaes/models/properties/modular_properties/state_definitions/FcPh.py
- idaes/models/properties/modular_properties/state_definitions/tests/test_FPhx.py
- idaes/models/properties/modular_properties/state_definitions/tests/test_FTPx.py
- idaes/models/properties/modular_properties/state_definitions/tests/test_FcPh.py
- idaes/models/properties/modular_properties/state_definitions/tests/test_FcTP.py
- idaes/models/properties/modular_properties/state_definitions/tests/test_FpcTP.py
Issue #1483 identified that enthalpy-based state definitions in the modular property framework triggered calls to components constructed by the equation of state module before these had been instantiated. This PR defers the construction of the constraint relating total molar enthalpy to the phase molar enthalpies until after the EoS components have been instantiated.
- Defer construction of `enth_mol_eqn` in enthalpy based state definitions.
- Fix some issues of cross-contamination in tests resulting in unexpected behaviors with this change
- Added units to partial molar enthalpy in DummyEoS to address unit consistency issue in tests
1. I agree my contributions are submitted under …
> Fix issue with enthalpy based states trying to use EoS before construciton

- idaes/models/properties/modular_properties/base/generic_property.py
- idaes/models/properties/modular_properties/base/generic_reaction.py
- idaes/models/properties/modular_properties/base/tests/test_generic_property.py
- idaes/models/properties/modular_properties/base/tests/test_generic_reaction.py
The Modular Properties did not give very useful error messages when given a dict of arguments instead of the unpacked arguments (`**kwargs`).
- Add catches for cases where when the dict might not have been unpacked and raise a useful error message.
-
> Better error messages for Modular Properties when config dict in not unpacked

- setup.py
Checking for issues ahead of the Pyomo release
- Bumping the IDAES tag of Pyomo to test against Pyomo main
> Bumping the IDAES tag of Pyomo to check for issues

- requirements-dev.txt
> Prune down unused dev dependencies

- .github/workflows/integration.yml
- docs/tutorials/getting_started/install_templates/conda_idaes_pse.txt
- docs/tutorials/getting_started/install_templates/quickstart.txt
> Update conda install commands after idaes-pse was added to conda-forge

- docs/reference_guides/core/control_volume_0d.rst
- docs/reference_guides/core/control_volume_1d.rst
- idaes/core/__init__.py
- idaes/core/base/control_volume0d.py
- idaes/core/base/control_volume1d.py
- idaes/core/base/control_volume_base.py
- idaes/core/base/extended_control_volume0d.py
- idaes/core/base/extended_control_volume1d.py
- idaes/core/base/tests/test_control_volume_0d.py
- idaes/core/base/tests/test_control_volume_1d.py
- idaes/core/base/tests/test_control_volume_base.py
- idaes/core/base/tests/test_extended_control_volume_0d.py
- idaes/core/base/tests/test_extended_control_volume_1d.py
WateTAP has a number of cases where they would like to use isothermal conditions in place of an energy balance. Currently, they use a mix-in to support this, but this adds an addition argument that is effectively redundant. Instead, it would be better to have explicit support for isothermal conditions as part of the core ControlVolume classes.
However, isothermal conditions do not make sense for all unit models, and there are a few cases where unit models have effectively implemented their own isothermal conditions (notable PressureChanger). Thus, to avoid potential edge cases in unit models until they can be updated, a new ExtendedControlVolume0D and ExtenededControlVolume1D class have been created as an interim solution. It is envisioned that unit models will gradually be updated to be …
> Add support for isothermal conditions in control volumes.

- .readthedocs.yml
RTD now requires an explicit path to the `conf.py` file
- Add explicit path
> Add explicit configuration path for ReadtheDocs

- .github/actions/setup-idaes/action.yml
- .github/workflows/core.yml
- .github/workflows/integration.yml
- idaes/config.py
Try the easiest possible way to resolve #1557 and similar issues before new `idaes-ext` builds are available
- Add mapping in `idaes/config.py` to use existing ubuntu2204 version if ubuntu2404 is detected
- Add ubuntu22.04 and 24.04 to CI job matrix
> Add mapping to use ubuntu2204 build of idaes-ext on Ubuntu 24.04

- requirements-dev.txt
Doctests started failing with the latest Sphinx release. We noticed similar issues in Pyomo that could be traced to Sphinx extensions that don't yet support Sphinx 8.2.0. This PR excludes this version of Sphinx for now to get IDAES tests passing again. I haven't identified which Sphinx extension is the underlying cause of the issue.
- Exclude Sphinx version 8.2.0
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I …
> Temporarily exclude sphinx 8.2.0 to fix doctests

- docs/tutorials/advanced_install/index.rst
- idaes/models/properties/general_helmholtz/helmholtz_functions.py
- The units on the labels for PH and TS diagrams did not update when changing the amount basis
- The documentation was outdated regarding the availability of macOS binaries
- Added logic to detect `amount_basis` and update the units accordingly
- Verified results for R134a against https://www.imperial.ac.uk/media/imperial-college/research-centres-and-groups/thermophysics/Chart-p-h-R134a.pdf
- Minor update to installation documentation …
> Two quick fixes: units on PH and TS diagrams, documentation for macOS

- docs/reference_guides/model_libraries/generic/unit_models/pressure_changer.rst
- Copy/past typo in the documentation
- Replaces "isothermal" with "adiabatic"
> Fixed typo/mistake in documentation

- idaes/core/util/math.py
- idaes/core/util/tests/test_math.py
Addresses a comment made [here](https://github.com/watertap-org/watertap/pull/1563#discussion_r2019371484) to add the smooth_heaviside function into IDAES rather than WaterTAP
- Adds the smooth_heaviside function to math
- Updates the testing
> Add Smooth Heaviside Function to Math

- idaes/core/util/model_diagnostics.py
- idaes/core/util/tests/test_model_diagnostics.py
Addresses an issue in https://github.com/watertap-org/watertap/pull/1563 where tests are passing locally but failing on GitHub. This is believed to be a result of this tool defaulting the solver to ipopt, whereas WaterTAP requires ipopt-watertap.
- Adds a config option to IPOPTConvergenceAnalysis
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required …
> Add Solver Config Option to IPOPT Convergence Analysis

- .github/actions/run-examples/action.yml
- .github/actions/run-examples/examples_for_idaes_ci.py
We recently found out that the integration tests only running the notebooks can actually cause us to miss some regressions between idaes-pse and examples (see PR #1677 ). This turns on testing both notebooks _and_ `test_*.py` files in the `examples` repo as part of the integration tests.
- Introduce new environment variables to control both notebook and `.py` files into the driver
- Modify the action appropriately …
> Test `.py` files from `examples` as part of Integration tests

- .github/workflows/core.yml
- .github/workflows/integration.yml
- README.md
- docs/conf.py
- requirements-dev.txt
- setup.py
[Issue 1668](https://github.com/IDAES/idaes-pse/issues/1668)
Catch up to current python releases. 3.14 will be released soon so understanding is supporting 3.13 is possible with the current state.
- Add 3.13 python to the current workflow
-
Notes
current version …
> Add testing 3.13 python to workflow
